/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.api;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.Unmodifiable;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

/**
 * Renders the API vhost's admission from the frozen contract set (REQ-API-021, REQ-OPS-042,
 * ADR-0135).
 *
 * <p>The vhost admits exactly the frozen operations, the two anonymous reads and the retired
 * operations, each as one anchored regular expression on {@code "$request_method:$uri"} in one
 * nginx {@code map}; every other verb and path is refused with {@code 404}. The same model yields
 * the nightly probe's table and the requests the live-nginx test drives. {@code ./gradlew
 * :backend:generateEdgeAdmission} writes the generated files.
 */
final class EdgeAdmission {

  /** The generated {@code map}, included at {@code http} level by the API vhost template. */
  static final String MAP_FILE = "docker/edge/include/api-admission.conf";

  /** The generated refusal, included inside the API vhost's {@code server} block. */
  static final String INCLUDE_FILE = "docker/edge/include/api-allowlist.conf";

  /** The nightly probe whose API vhost table is generated between {@link #PROBE_START} and end. */
  static final String PROBE_WORKFLOW = ".github/workflows/edge-deny-probe.yml";

  /** The first line of every generated file. */
  static final String GENERATED_HEADER =
      "# Generated by EdgeAdmission from the frozen contract set -- do not edit."
          + " Run ./gradlew :backend:generateEdgeAdmission.";

  /** The line opening the admission map. */
  static final String MAP_OPEN = "map \"$request_method:$uri\" $krt_api_admitted {";

  /** The map's default: refused. */
  static final String MAP_DEFAULT = "  default 0;";

  /** The line in the probe workflow after which the generated rows start. */
  static final String PROBE_START = "          done <<'PROBES'";

  /** The line in the probe workflow that ends the generated rows. */
  static final String PROBE_END = "          PROBES";

  /** The indentation of a probe row inside the workflow's {@code run} block. */
  private static final String PROBE_INDENT = "          ";

  /** The anonymous reads (REQ-SEC-037), admitted whether or not the frozen set lists them. */
  static final Set<String> ANONYMOUS_READS =
      Set.of("GET /api/v1/app/version-policy", "GET /api/v1/terms/document");

  /** The verbs the refusal matrix tries on every admitted path. */
  static final List<String> VERBS =
      List.of("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS");

  /** The verbs, in order of preference, from which the probe samples one refusal per path. */
  private static final List<String> PROBE_REFUSAL_VERBS =
      List.of("GET", "POST", "PUT", "PATCH", "DELETE");

  /** The id shape every uuid placeholder admits. */
  static final String UUID_REGEX =
      "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}";

  /** The id the probe and the matrix send; authorization is decided before any lookup. */
  static final String SAMPLE_UUID = "00000000-0000-4000-8000-00000000cafe";

  /** The shape of a uuid placeholder. */
  private static final Shape UUID_SHAPE = new Shape(UUID_REGEX, List.of(SAMPLE_UUID));

  /** The shape of a boolean placeholder. */
  private static final Shape BOOLEAN_SHAPE = new Shape("(true|false)", List.of("true", "false"));

  /**
   * The reviewed shapes of placeholders that are neither uuids nor booleans, by placeholder name.
   */
  private static final Map<String, Shape> NAMED_SHAPES =
      Map.of(
          "roleCode",
          new Shape("[A-Za-z0-9_-]{1,64}", List.of("LOGISTICIAN")),
          "type",
          new Shape("[A-Z][A-Z0-9_]{1,63}", List.of("JOB_ORDER_CREATED")),
          "key",
          new Shape(
              "(job_order\\.age_yellow_days|job_order\\.age_red_days)",
              List.of("job_order.age_yellow_days", "job_order.age_red_days")));

  /** A literal path segment: no character a regular expression would read as syntax but a dot. */
  private static final Pattern LITERAL_SEGMENT = Pattern.compile("[A-Za-z0-9_~.-]+");

  /** A placeholder path segment. */
  private static final Pattern PLACEHOLDER_SEGMENT = Pattern.compile("\\{([A-Za-z][A-Za-z0-9]*)}");

  /** One operation as written in the frozen set, the anonymous reads or the retired list. */
  private static final Pattern OPERATION = Pattern.compile("^([A-Z]+) (/api/\\S+)$");

  /** One admission entry of the committed map: group 1 the verb, group 2 the path expression. */
  private static final Pattern MAP_ENTRY =
      Pattern.compile("^  \"~\\^([A-Z]+):(/[^\"$^]+)\\$\" 1;$");

  /**
   * Requests no admitted operation may match, each refused with {@code 404}: the paths the removed
   * prefix rules opened, the web-only admin trees, the exchange, near-misses of admitted paths, and
   * the verbs the anonymous reads do not admit.
   */
  static final List<Request> NEAR_MISSES =
      List.of(
          refused("GET", "/api/v1/me/layout"),
          refused("GET", "/api/v1/me/a-path-not-built-yet"),
          refused("GET", "/api/v1/terms/admin"),
          refused("GET", "/api/v1/terms/admin/pending-count"),
          refused("GET", "/api/v1/terms/a-path-not-built-yet"),
          refused("GET", "/api/v1/terms/admin"),
          refused("HEAD", "/api/v1/terms/document"),
          refused("HEAD", "/api/v1/app/version-policy"),
          refused("POST", "/api/v1/app/version-policy"),
          refused("GET", "/api/v1/exchange/me/blueprints"),
          refused("GET", "/api/v1/connected-apps"),
          refused("GET", "/api/v1/definitely-not-allow-listed"),
          refused("GET", "/api/v1/missions"),
          refused("POST", "/api/v1/missions"),
          refused("POST", "/api/v1/users"),
          refused("GET", "/api/v1/operations"),
          refused("POST", "/api/v1/operations/"),
          refused("POST", "/api/v1/Operations"),
          refused("POST", "/api/v1/operation"),
          refused("POST", "/api/v1/operations%2F"),
          refused("PUT", "/api/v1/orders/not-a-uuid/requested"),
          refused("PUT", "/api/v1/orders/requested"),
          refused("POST", "/api/v1/refinery-orders/import-extract"),
          refused("POST", "/api/v1/missions/" + SAMPLE_UUID + "/participants"),
          refused("POST", "/api/v1/missions/" + SAMPLE_UUID + "/participants/slim"),
          refused("GET", "/api/v1/hangar/admin/users/" + SAMPLE_UUID + "/ships"),
          refused("GET", "/api/v1/bank/accounts/" + SAMPLE_UUID + "/balance-series"),
          refused("GET", "/api/v1/bank/admin/audit"),
          refused("POST", "/api/v1/bank/admin/wipe-reset"),
          refused("PATCH", "/api/v1/bank/accounts/" + SAMPLE_UUID + "/approval-tiers"),
          refused("POST", "/api/v1/inventory/all"),
          refused("GET", "/api/v1/settings/job_order.age_green_days"),
          refused(
              "PUT",
              "/api/v1/org-units/bank/accounts/" + SAMPLE_UUID + "/visibility/all-members/maybe"),
          refused("GET", "/api/v2/ping"),
          refused("GET", "/actuator/health"));

  /** The admitted operations, ordered by path and then by verb. */
  private final @NotNull @Unmodifiable List<Operation> operations;

  /**
   * Creates the model over already-built operations.
   *
   * @param operations the admitted operations, ordered by path and then by verb
   */
  private EdgeAdmission(@NotNull List<Operation> operations) {
    this.operations = List.copyOf(operations);
  }

  /**
   * Where an admitted operation comes from, and what an anonymous caller gets from it.
   *
   * <p>The status is what the nightly probe asserts from outside and the backend test pins inside.
   */
  @Getter
  @RequiredArgsConstructor
  enum Source {
    /** A frozen operation: the backend refuses an anonymous caller. */
    FROZEN(401),
    /** One of the two anonymous reads. */
    ANONYMOUS(200),
    /** A retired operation: {@code APP_UPDATE_REQUIRED}, ahead of authentication. */
    RETIRED(410);

    /** The status an anonymous request gets once it has passed the edge. */
    private final int anonymousStatus;
  }

  /**
   * What a path placeholder admits.
   *
   * @param regex the regular expression for one segment, without anchors
   * @param samples values that match it, the first one the probe's
   */
  record Shape(@NotNull String regex, @NotNull @Unmodifiable List<String> samples) {}

  /**
   * One admitted operation.
   *
   * @param method the HTTP verb, upper case
   * @param path the path template exactly as the source writes it
   * @param source where the operation comes from
   * @param pathRegex the path as a regular expression, without anchors
   * @param samples concrete paths the operation admits, the first one the probe's
   */
  record Operation(
      @NotNull String method,
      @NotNull String path,
      @NotNull Source source,
      @NotNull String pathRegex,
      @NotNull @Unmodifiable List<String> samples) {

    /**
     * Identifies the operation as {@code VERB path}.
     *
     * @return the verb and the path template, separated by one space
     */
    @NotNull
    String key() {
      return method + " " + path;
    }

    /**
     * Renders the operation's line of the admission map.
     *
     * @return the indented, quoted, anchored entry mapping to {@code 1}
     */
    @NotNull
    String mapEntry() {
      return "  \"~^" + method + ":" + pathRegex + "$\" 1;";
    }

    /**
     * Compiles the entry's expression as nginx evaluates it on {@code "$request_method:$uri"}.
     *
     * @return the anchored pattern
     */
    @NotNull
    Pattern pattern() {
      return Pattern.compile("^" + method + ":" + pathRegex + "$");
    }
  }

  /**
   * One request and the status the edge must answer.
   *
   * @param method the HTTP verb
   * @param path the request path, possibly with a query string
   * @param status the expected status
   */
  record Request(@NotNull String method, @NotNull String path, int status) {

    /**
     * Renders the request as a row of the probe table.
     *
     * @return {@code VERB path status}
     */
    @NotNull
    String row() {
      return method + " " + path + " " + status;
    }
  }

  /**
   * Builds the model from the frozen set, the committed API document and, when present, the
   * committed list of retired operations.
   *
   * @return the model
   * @throws IOException if a resource cannot be read
   */
  static @NotNull EdgeAdmission load() throws IOException {
    JsonNode document;
    try (InputStream in = EdgeAdmission.class.getResourceAsStream("/api/openapi.json")) {
      if (in == null) {
        throw new IOException("/api/openapi.json is not on the classpath");
      }
      document = new ObjectMapper().readTree(in);
    }
    return of(ExternalContractTest.frozenOperations(), retiredOperations(), document);
  }

  /**
   * Reads the retired operations off the classpath (REQ-API-020).
   *
   * @return the entries as {@code VERB path}; empty when the list is absent or empty
   * @throws IOException if the list exists and cannot be read
   */
  static @NotNull @Unmodifiable List<String> retiredOperations() throws IOException {
    try (InputStream in = EdgeAdmission.class.getResourceAsStream("/api/retired-operations.txt")) {
      if (in == null) {
        return List.of();
      }
      return new String(in.readAllBytes(), StandardCharsets.UTF_8)
          .lines()
          .map(String::strip)
          .filter(line -> !line.isEmpty())
          .toList();
    }
  }

  /**
   * Builds the model.
   *
   * @param frozen the frozen operations as {@code VERB path}
   * @param retired the retired operations as {@code VERB path}
   * @param document the API document the frozen operations' placeholder types are read from
   * @return the model, ordered by path and then by verb
   * @throws IllegalArgumentException if an operation is malformed or listed twice, a frozen
   *     operation is missing from the document, a retired one is still frozen, or a placeholder has
   *     no reviewed shape
   */
  static @NotNull EdgeAdmission of(
      @NotNull Collection<String> frozen,
      @NotNull Collection<String> retired,
      @NotNull JsonNode document) {
    Map<String, Operation> byKey = new LinkedHashMap<>();
    for (String key : frozen) {
      Source source = ANONYMOUS_READS.contains(key) ? Source.ANONYMOUS : Source.FROZEN;
      add(byKey, key, source, document);
    }
    for (String key : new TreeSet<>(ANONYMOUS_READS)) {
      if (!byKey.containsKey(key)) {
        add(byKey, key, Source.ANONYMOUS, document);
      }
    }
    for (String key : retired) {
      if (byKey.containsKey(normalise(key))) {
        throw new IllegalArgumentException("retired and admitted at once: " + key);
      }
      add(byKey, key, Source.RETIRED, null);
    }
    List<Operation> sorted = new ArrayList<>(byKey.values());
    sorted.sort(
        Comparator.comparing(Operation::path)
            .thenComparing(operation -> VERBS.indexOf(operation.method())));
    return new EdgeAdmission(sorted);
  }

  /**
   * Upper-cases the verb of an operation key.
   *
   * @param key {@code VERB path}
   * @return the key with its verb upper case
   */
  private static String normalise(String key) {
    int space = key.indexOf(' ');
    return space < 0
        ? key
        : key.substring(0, space).toUpperCase(Locale.ROOT) + key.substring(space);
  }

  /**
   * Builds one operation and adds it.
   *
   * @param byKey the operations built so far
   * @param raw the operation as {@code VERB path}
   * @param source where it comes from
   * @param document the API document, or {@code null} for a retired operation
   * @throws IllegalArgumentException if the operation is malformed or already present
   */
  private static void add(
      Map<String, Operation> byKey, String raw, Source source, @Nullable JsonNode document) {
    String key = normalise(raw.strip());
    Matcher matcher = OPERATION.matcher(key);
    if (!matcher.matches() || !VERBS.contains(matcher.group(1))) {
      throw new IllegalArgumentException("not 'VERB /api/path': " + raw);
    }
    String method = matcher.group(1);
    String path = matcher.group(2);
    Map<String, Shape> shapes =
        document == null ? retiredShapes(path) : documentedShapes(document, method, path);
    StringBuilder regex = new StringBuilder();
    List<List<String>> segmentSamples = new ArrayList<>();
    for (String segment : path.substring(1).split("/", -1)) {
      regex.append('/');
      Matcher placeholder = PLACEHOLDER_SEGMENT.matcher(segment);
      if (placeholder.matches()) {
        Shape shape = shapes.get(placeholder.group(1));
        regex.append(shape.regex());
        segmentSamples.add(shape.samples());
      } else if (LITERAL_SEGMENT.matcher(segment).matches()) {
        regex.append(segment.replace(".", "\\."));
        segmentSamples.add(List.of(segment));
      } else {
        throw new IllegalArgumentException("not a literal or {placeholder} segment: " + raw);
      }
    }
    int width = segmentSamples.stream().mapToInt(List::size).max().orElse(1);
    Set<String> samples = new LinkedHashSet<>();
    for (int index = 0; index < width; index++) {
      StringBuilder sample = new StringBuilder();
      for (List<String> values : segmentSamples) {
        sample.append('/').append(values.get(Math.min(index, values.size() - 1)));
      }
      samples.add(sample.toString());
    }
    Operation operation =
        new Operation(method, path, source, regex.toString(), List.copyOf(samples));
    if (byKey.putIfAbsent(key, operation) != null) {
      throw new IllegalArgumentException("listed twice: " + raw);
    }
  }

  /**
   * Reads the shape of every path placeholder of a documented operation from its parameters.
   *
   * @param document the API document
   * @param method the verb, upper case
   * @param path the path template
   * @return the shapes by placeholder name
   * @throws IllegalArgumentException if the document lacks the operation or a placeholder has no
   *     reviewed shape
   */
  private static Map<String, Shape> documentedShapes(
      JsonNode document, String method, String path) {
    JsonNode operation = document.path("paths").path(path).path(method.toLowerCase(Locale.ROOT));
    if (operation.isMissingNode()) {
      throw new IllegalArgumentException("frozen but not in openapi.json: " + method + " " + path);
    }
    Map<String, Shape> shapes = new TreeMap<>();
    for (JsonNode parameter : operation.path("parameters")) {
      if (!"path".equals(parameter.path("in").asString(""))) {
        continue;
      }
      String name = parameter.path("name").asString("");
      JsonNode schema = parameter.path("schema");
      Shape shape;
      if ("uuid".equals(schema.path("format").asString(""))) {
        shape = UUID_SHAPE;
      } else if ("boolean".equals(schema.path("type").asString(""))) {
        shape = BOOLEAN_SHAPE;
      } else {
        shape = NAMED_SHAPES.get(name);
      }
      if (shape == null) {
        throw new IllegalArgumentException(
            "{"
                + name
                + "} of "
                + method
                + " "
                + path
                + " is neither a uuid nor a boolean and has no reviewed shape in NAMED_SHAPES");
      }
      shapes.put(name, shape);
    }
    return shapes;
  }

  /**
   * Assigns the shapes of a retired operation's placeholders, which the document no longer
   * describes: a reviewed named shape, else a uuid for {@code id} and every {@code …Id}.
   *
   * @param path the path template
   * @return the shapes by placeholder name
   * @throws IllegalArgumentException if a placeholder is neither named nor an id
   */
  private static Map<String, Shape> retiredShapes(String path) {
    Map<String, Shape> shapes = new TreeMap<>();
    Matcher placeholder = Pattern.compile("\\{([A-Za-z][A-Za-z0-9]*)}").matcher(path);
    while (placeholder.find()) {
      String name = placeholder.group(1);
      Shape shape = NAMED_SHAPES.get(name);
      if (shape == null && (name.equals("id") || name.endsWith("Id"))) {
        shape = UUID_SHAPE;
      }
      if (shape == null) {
        throw new IllegalArgumentException(
            "{" + name + "} of the retired " + path + " has no reviewed shape in NAMED_SHAPES");
      }
      shapes.put(name, shape);
    }
    return shapes;
  }

  /**
   * Builds a refusal row.
   *
   * @param method the verb
   * @param path the path
   * @return the request expecting {@code 404}
   */
  private static Request refused(String method, String path) {
    return new Request(method, path, 404);
  }

  /**
   * Returns the admitted operations.
   *
   * @return the operations, ordered by path and then by verb
   */
  @NotNull
  @Unmodifiable
  List<Operation> operations() {
    return operations;
  }

  /**
   * Returns the admitted operations' keys.
   *
   * @return every admitted operation as {@code VERB path}
   */
  @NotNull
  Set<String> keys() {
    Set<String> keys = new LinkedHashSet<>();
    operations.forEach(operation -> keys.add(operation.key()));
    return keys;
  }

  /**
   * Tells whether the model admits a request.
   *
   * @param method the verb
   * @param uri the decoded path without a query string
   * @return {@code true} when an admitted operation's expression matches
   */
  boolean admits(@NotNull String method, @NotNull String uri) {
    String subject = method + ":" + uri;
    return operations.stream()
        .anyMatch(operation -> operation.pattern().matcher(subject).matches());
  }

  /**
   * Renders the admission map.
   *
   * @return the file's content, LF line endings
   */
  @NotNull
  String renderMap() {
    StringBuilder out = new StringBuilder();
    out.append(GENERATED_HEADER).append('\n');
    out.append(MAP_OPEN).append('\n');
    out.append(MAP_DEFAULT).append('\n');
    operations.forEach(operation -> out.append(operation.mapEntry()).append('\n'));
    out.append("}\n");
    return out.toString();
  }

  /**
   * Renders the server-level include: the one refusal, the actuator deny and the body limit.
   *
   * @return the file's content, LF line endings
   */
  @NotNull
  static String renderInclude() {
    return GENERATED_HEADER
        + "\n"
        + "if ($krt_api_admitted = 0) { return 404; }\n"
        + "\n"
        + "location /actuator { return 404; }\n"
        + "\n"
        + "client_max_body_size 4m;\n";
  }

  /**
   * Lists the admitted paths with the verbs admitted on each and their samples.
   *
   * @return the admitted verbs by path template, in path order
   */
  private Map<String, Set<String>> verbsByPath() {
    Map<String, Set<String>> verbs = new LinkedHashMap<>();
    operations.forEach(
        operation ->
            verbs
                .computeIfAbsent(operation.path(), path -> new LinkedHashSet<>())
                .add(operation.method()));
    return verbs;
  }

  /**
   * Finds the first operation on a path, whose samples stand for the path.
   *
   * @param path the path template
   * @return the operation
   */
  private Operation firstOn(String path) {
    return operations.stream()
        .filter(operation -> operation.path().equals(path))
        .findFirst()
        .orElseThrow();
  }

  /**
   * Lists the nightly probe's rows: every admitted operation with its anonymous status, one refused
   * verb per admitted path, and the near-misses.
   *
   * @return the rows in a stable order, each request once
   */
  @NotNull
  List<Request> probeRows() {
    List<Request> rows = new ArrayList<>();
    operations.forEach(
        operation ->
            rows.add(
                new Request(
                    operation.method(),
                    operation.samples().getFirst(),
                    operation.source().getAnonymousStatus())));
    verbsByPath()
        .forEach(
            (path, admitted) ->
                PROBE_REFUSAL_VERBS.stream()
                    .filter(verb -> !admitted.contains(verb))
                    .findFirst()
                    .ifPresent(
                        verb -> rows.add(refused(verb, firstOn(path).samples().getFirst()))));
    rows.addAll(NEAR_MISSES);
    return dedupe(rows);
  }

  /**
   * Lists every request the live-nginx test expects to reach the upstream: each sample of each
   * admitted operation, bare and with a query string.
   *
   * @return the requests expecting {@code 200}
   */
  @NotNull
  List<Request> admittedRequests() {
    List<Request> requests = new ArrayList<>();
    for (Operation operation : operations) {
      for (String sample : operation.samples()) {
        requests.add(new Request(operation.method(), sample, 200));
        requests.add(new Request(operation.method(), sample + "?probe=1", 200));
      }
    }
    return dedupe(requests);
  }

  /**
   * Lists every request the live-nginx test expects the edge to refuse: each verb an admitted path
   * does not admit, near-miss spellings of every admitted path, a non-uuid in each uuid position,
   * and the near-misses.
   *
   * @return the requests expecting {@code 404}
   */
  @NotNull
  List<Request> refusedRequests() {
    List<Request> candidates = new ArrayList<>();
    verbsByPath()
        .forEach(
            (path, admitted) -> {
              List<String> samples = firstOn(path).samples();
              for (String verb : VERBS) {
                if (!admitted.contains(verb)) {
                  samples.forEach(sample -> candidates.add(refused(verb, sample)));
                }
              }
            });
    for (Operation operation : operations) {
      String sample = operation.samples().getFirst();
      String method = operation.method();
      candidates.add(refused(method, sample + "/"));
      candidates.add(refused(method, sample + "X"));
      candidates.add(refused(method, sample + "/extra"));
      if (sample.startsWith("/api/v1/")) {
        candidates.add(refused(method, capitaliseFirstResource(sample)));
        candidates.add(refused(method, sample.replace("/api/v1/", "/api/v2/")));
      }
      if (sample.contains(SAMPLE_UUID)) {
        candidates.add(refused(method, sample.replaceFirst(SAMPLE_UUID, "not-a-uuid")));
        candidates.add(refused(method, sample.replaceFirst(SAMPLE_UUID, SAMPLE_UUID + "0")));
      }
    }
    candidates.addAll(NEAR_MISSES);
    return dedupe(
        candidates.stream()
            .filter(request -> !admits(request.method(), decodedPath(request.path())))
            .toList());
  }

  /**
   * Upper-cases the first letter of the resource after {@code /api/v1/}.
   *
   * @param sample a concrete path under {@code /api/v1/}
   * @return the path differing only in that letter's case
   */
  private static String capitaliseFirstResource(String sample) {
    int at = "/api/v1/".length();
    return sample.substring(0, at)
        + Character.toUpperCase(sample.charAt(at))
        + sample.substring(at + 1);
  }

  /**
   * Decodes {@code %2F} the way nginx normalises {@code $uri}, which is what the map reads.
   *
   * @param path the request path
   * @return the path nginx matches
   */
  static @NotNull String decodedPath(@NotNull String path) {
    int query = path.indexOf('?');
    String bare = query < 0 ? path : path.substring(0, query);
    return bare.replace("%2F", "/").replace("%2f", "/");
  }

  /**
   * Removes repeated requests, keeping the first.
   *
   * @param requests the requests
   * @return the requests without a repeated verb and path
   * @throws IllegalStateException if one verb and path is expected to answer two statuses
   */
  private static List<Request> dedupe(List<Request> requests) {
    Map<String, Request> seen = new LinkedHashMap<>();
    for (Request request : requests) {
      Request before = seen.putIfAbsent(request.method() + " " + request.path(), request);
      if (before != null && before.status() != request.status()) {
        throw new IllegalStateException(
            "conflicting expectations for "
                + request.method()
                + " "
                + request.path()
                + ": "
                + before.status()
                + " and "
                + request.status());
      }
    }
    return List.copyOf(seen.values());
  }

  /**
   * Replaces the probe workflow's generated rows.
   *
   * @param workflow the workflow's current content
   * @return the content with the rows between {@link #PROBE_START} and {@link #PROBE_END}
   *     regenerated, LF line endings
   * @throws IllegalStateException if the markers are missing
   */
  @NotNull
  String renderProbeWorkflow(@NotNull String workflow) {
    List<String> lines = workflow.replace("\r\n", "\n").lines().toList();
    int start = lines.indexOf(PROBE_START);
    int end = start < 0 ? -1 : lines.subList(start + 1, lines.size()).indexOf(PROBE_END);
    if (start < 0 || end < 0) {
      throw new IllegalStateException(
          PROBE_WORKFLOW + " has no '" + PROBE_START.strip() + "' … '" + PROBE_END.strip() + "'");
    }
    List<String> out = new ArrayList<>(lines.subList(0, start + 1));
    probeRows().forEach(row -> out.add(PROBE_INDENT + row.row()));
    out.addAll(lines.subList(start + 1 + end, lines.size()));
    return String.join("\n", out) + "\n";
  }

  /**
   * Reads the probe workflow's rows.
   *
   * @param workflow the workflow's content
   * @return the rows between the markers, parsed
   * @throws IllegalStateException if the markers are missing or a row is malformed
   */
  static @NotNull List<Request> parseProbeRows(@NotNull String workflow) {
    List<String> lines = workflow.replace("\r\n", "\n").lines().toList();
    int start = lines.indexOf(PROBE_START);
    if (start < 0) {
      throw new IllegalStateException(PROBE_WORKFLOW + " has no '" + PROBE_START.strip() + "'");
    }
    List<Request> rows = new ArrayList<>();
    for (String line : lines.subList(start + 1, lines.size())) {
      if (line.equals(PROBE_END)) {
        return rows;
      }
      String[] parts = line.strip().split(" ");
      if (parts.length != 3 || !parts[2].matches("\\d{3}")) {
        throw new IllegalStateException("malformed probe row: " + line);
      }
      rows.add(new Request(parts[0], parts[1], Integer.parseInt(parts[2])));
    }
    throw new IllegalStateException(PROBE_WORKFLOW + " has no '" + PROBE_END.strip() + "'");
  }

  /**
   * Parses a committed admission map strictly, so that no line can admit a request the parse does
   * not see.
   *
   * @param lines the file's lines
   * @return one anchored pattern per admission entry, evaluated on {@code "VERB:uri"}
   * @throws AssertionError naming the first line that is neither the header, the opening, the
   *     default, an anchored entry mapping to {@code 1}, nor the closing brace
   */
  static @NotNull List<Pattern> parseMap(@NotNull List<String> lines) {
    List<Pattern> entries = new ArrayList<>();
    boolean opened = false;
    boolean defaulted = false;
    boolean closed = false;
    for (int index = 0; index < lines.size(); index++) {
      String line = lines.get(index).replace("\r", "");
      if (line.isBlank()) {
        continue;
      }
      Matcher entry = MAP_ENTRY.matcher(line);
      if (!opened && line.startsWith("#")) {
        continue;
      } else if (!opened && line.equals(MAP_OPEN)) {
        opened = true;
      } else if (opened && !defaulted && !closed && line.equals(MAP_DEFAULT)) {
        defaulted = true;
      } else if (defaulted && !closed && entry.matches()) {
        entries.add(Pattern.compile("^" + entry.group(1) + ":" + entry.group(2) + "$"));
      } else if (defaulted && !closed && line.equals("}")) {
        closed = true;
      } else {
        throw new AssertionError(
            String.format(
                "%s line %d is not a line of the generated admission map, so no test can say"
                    + " what it admits: %s. Regenerate the file with ./gradlew"
                    + " :backend:generateEdgeAdmission",
                MAP_FILE, index + 1, line.strip()));
      }
    }
    if (!closed) {
      throw new AssertionError(MAP_FILE + " has no complete map block");
    }
    return entries;
  }

  /**
   * Compares a parsed admission map with the model in both directions, by sample.
   *
   * @param entries the parsed entries
   * @return one line per operation no entry admits, per operation more than one entry admits, and
   *     per entry that admits no operation; empty when the map admits exactly the model
   */
  @NotNull
  List<String> differencesFrom(@NotNull List<Pattern> entries) {
    List<String> problems = new ArrayList<>();
    boolean[] used = new boolean[entries.size()];
    for (Operation operation : operations) {
      for (String sample : operation.samples()) {
        String subject = operation.method() + ":" + sample;
        int matching = 0;
        for (int index = 0; index < entries.size(); index++) {
          if (entries.get(index).matcher(subject).matches()) {
            matching++;
            used[index] = true;
          }
        }
        if (matching == 0) {
          problems.add(operation.key() + " is admitted by the model, but no map entry admits it");
        } else if (matching > 1) {
          problems.add(operation.key() + " is admitted by " + matching + " map entries");
        }
      }
    }
    for (int index = 0; index < entries.size(); index++) {
      if (!used[index]) {
        problems.add(
            "the map entry /"
                + entries.get(index).pattern()
                + "/ admits no operation of the model");
      }
    }
    return problems;
  }

  /**
   * Writes the generated files under the repository root.
   *
   * @param args one argument: the repository root
   * @throws IOException if a file cannot be read or written
   */
  public static void main(String[] args) throws IOException {
    if (args.length != 1) {
      throw new IllegalArgumentException("usage: EdgeAdmission <repository root>");
    }
    Path root = Path.of(args[0]);
    EdgeAdmission admission = load();
    Files.writeString(root.resolve(MAP_FILE), admission.renderMap(), StandardCharsets.UTF_8);
    Files.writeString(root.resolve(INCLUDE_FILE), renderInclude(), StandardCharsets.UTF_8);
    Path workflow = root.resolve(PROBE_WORKFLOW);
    Files.writeString(
        workflow,
        admission.renderProbeWorkflow(Files.readString(workflow, StandardCharsets.UTF_8)),
        StandardCharsets.UTF_8);
  }
}
