version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: docker
    directory: /docker/app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: docker
    directory: /.github/actions/setup-buildx
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "chore(compose)"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - dependencies
    commit-message:
      prefix: "chore(npm)"
