test.maxHeap=2048m
coverage.instruction=0.60
coverage.branch=0.46
mutation.targetClasses=de.greluc.krt.profit.basetool.frontend.service.*
mutation.targetTests=de.greluc.krt.profit.basetool.frontend.service.*Test
