/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * A Kommandogruppe (command group) within a Staffel, led by a {@link
 * MembershipRole#KOMMANDOLEITER}, deputised by a {@link MembershipRole#STELLV_KOMMANDOLEITER}, with
 * {@link MembershipRole#ENSIGN}s assigned (REQ-ROLE-003).
 *
 * <p>DB triggers cap a squadron at four groups and require {@link #squadron} to be a {@code
 * SQUADRON}-kind {@link OrgUnit}. Membership is held on {@link
 * OrgUnitMembership#getKommandoGroup()}. A group grants no rights by itself.
 */
@Entity
@Table(name = "kommando_group")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class KommandoGroup extends AbstractEntity<UUID> {

  /** Surrogate primary key, generated by Hibernate as a random UUID on first persist. */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * The Staffel this Kommandogruppe belongs to — a {@code SQUADRON}-kind {@link OrgUnit}. The
   * {@code validate_kommando_group_squadron} trigger (V185) rejects a non-SQUADRON reference; the
   * {@code enforce_max_four_kommando_groups_per_squadron} trigger caps the count at four per
   * squadron. Lazy-fetched so listing groups does not eagerly hydrate the org-unit row.
   */
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "squadron_org_unit_id", nullable = false)
  @ToString.Exclude
  private OrgUnit squadron;

  /**
   * Display name of the Kommandogruppe (free text, e.g. "Alpha", "Jagd"). Not unique within a
   * squadron — ordering is by {@link #sortIndex}. Capped at 120 chars by the column definition.
   */
  @Column(name = "name", nullable = false, length = 120)
  private String name;

  /**
   * Stable display order of this group among its squadron's groups (ascending). Lets the UI render
   * the up-to-four groups in a deterministic, admin-controlled sequence rather than by insertion
   * time or id.
   */
  @Column(name = "sort_index", nullable = false)
  private int sortIndex;
}
