/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.DiscriminatorType;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Abstract base entity for the {@code org_unit} table — the shared parent of every tenant kind the
 * application recognises. Concrete subclasses use {@link OrgUnitKind} as a string discriminator on
 * the {@code kind} column and inherit the common columns ({@code id}, {@code name}, {@code
 * shorthand}, {@code description}, {@code active}, {@code is_promotion_enabled}) plus the audit
 * fields supplied by {@link AbstractEntity}.
 *
 * <p>Why a single-table inheritance hierarchy: the application has historically used one tenant
 * kind ({@code Squadron}) and is now growing a second ({@link SpecialCommand}, introduced by the
 * Spezialkommando R2.a slice — see {@code SPEZIALKOMMANDO_PLAN.md} §3). Both kinds share exactly
 * the same column shape (the {@code squadron} table was duplicated 1:1 into {@code org_unit} by
 * Flyway migration V94, gaining only the {@code kind} discriminator), so flattening the polymorphic
 * data into one table avoids the joined-strategy join cost without paying any structural price.
 * Subclasses that need their own columns can move to joined-strategy later via a dedicated
 * migration; nothing in the current shape needs subclass-specific columns.
 *
 * <p><b>Squadron joined this hierarchy in R2.b.</b> The {@link Squadron} entity now maps to the
 * {@code org_unit} table via {@code @DiscriminatorValue("SQUADRON")}, alongside {@link
 * SpecialCommand}, so a polymorphic {@code OrgUnit} query materialises {@code kind='SQUADRON'} rows
 * as {@link Squadron} and {@code kind='SPECIAL_COMMAND'} rows as {@link SpecialCommand} ({@link
 * Bereich} and {@link Organisationsleitung} joined later, ADR-0025). The legacy {@code squadron}
 * mirror table and its sync trigger were dropped in V105, which retargeted the last {@code
 * squadron_id}-named foreign keys at {@code org_unit}. {@code OrgUnitMembership} stores {@code
 * org_unit_id} as a plain UUID rather than a JPA relation to {@code OrgUnit}, decoupling membership
 * rows from the entity hierarchy.
 *
 * <p>Promotion-feature invariant: {@link #isPromotionEnabled} stays on this superclass so the
 * {@code OwnerScopeService.isPromotionFeatureEnabledForCurrentScope} check can read it from a
 * polymorphic {@code OrgUnit} reference. The database CHECK constraint {@code
 * chk_org_unit_promotion_only_squadron} (V94) enforces that {@code is_promotion_enabled} is false
 * for every {@code SPECIAL_COMMAND} row, so a careless setter call on a {@link SpecialCommand}
 * instance surfaces as a constraint violation at flush time rather than silently exposing the
 * promotion menu to SK members.
 */
@Entity
@Table(name = "org_unit")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "kind", discriminatorType = DiscriminatorType.STRING, length = 32)
@Getter
@Setter
@ToString
@NoArgsConstructor
public abstract class OrgUnit extends AbstractEntity<UUID> {

  /**
   * Primary key, generated by Hibernate as a random UUID for new rows. The annotation also
   * overrides the {@link AbstractEntity#getId()} getter so {@link
   * org.springframework.data.domain.Persistable#getId()} resolves to the typed UUID field rather
   * than the erased base-class accessor.
   */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * Human-readable display name. Unique across all kinds (so a Spezialkommando cannot be named
   * "IRIDIUM" while the IRIDIUM squadron also exists), matching the {@code UNIQUE} constraint
   * inherited from the original {@code squadron} schema and preserved by V94.
   */
  @Column(unique = true, nullable = false)
  private String name;

  /**
   * Short identifier (3-5 letters) used in badges, chips, and audit logs. Unique across all kinds
   * for the same reasons as {@link #name}.
   */
  @Column(unique = true, nullable = false)
  private String shorthand;

  /** Free-text description shown on admin pages. May be {@code null} for newly-created rows. */
  @Column(columnDefinition = "TEXT")
  private String description;

  /**
   * Soft-delete flag. {@code false} hides the org unit from list views without deleting any data.
   * Defaults to {@code true} so a freshly-constructed entity goes straight into active state — the
   * existing {@code SquadronService.deleteSquadron} flow flips this rather than emitting a DELETE,
   * and {@link SpecialCommand} mirrors that behaviour.
   */
  @Column(nullable = false)
  private boolean active = true;

  /**
   * Per-org-unit feature flag deciding whether the promotion subsystem (topics, categories,
   * level-contents, rank-requirements, member-evaluations) is exposed to non-admin members of this
   * org unit. Default {@code true} so existing squadrons continue to expose the menu after the V86
   * migration that introduced the column. The V94 CHECK constraint {@code
   * chk_org_unit_promotion_only_squadron} forces this to {@code false} on every {@code
   * SPECIAL_COMMAND} row regardless of what the application tries to write, so admin tooling cannot
   * accidentally enable promotion on a Spezialkommando.
   */
  @Column(name = "is_promotion_enabled", nullable = false)
  private boolean isPromotionEnabled = true;

  /**
   * Per-org-unit eligibility flag deciding whether this org unit may be picked as the
   * <em>responsible (processing)</em> org unit of a Job Order. Applies to <b>both</b> kinds: only
   * org units that an admin has explicitly marked profit-eligible can process orders. Squadrons and
   * Spezialkommandos belong to different Kartell departments (Combat, Research, Profit, …) and only
   * the Profit-side units process orders — an SK of another department may still be the
   * <em>requesting</em> (placing) org unit but must not appear in the responsible picker. The flag
   * therefore defaults to {@code false} for every newly-created org unit (squadron or SK) and is
   * toggled exclusively through the dedicated {@code PATCH /api/v1/squadrons/{id}/profit-eligible}
   * / {@code PATCH /api/v1/special-commands/{id}/profit-eligible} endpoints, never as a side-effect
   * of a regular update, mirroring the {@link #isPromotionEnabled} handling.
   */
  @Column(name = "is_profit_eligible", nullable = false)
  private boolean isProfitEligible = false;

  /**
   * The Kartell department (and its frozen Bereichsfarbe) this org unit belongs to (epic #692,
   * REQ-ORG-026). Meaningful only for a {@link Bereich} — it drives the per-Bereich colour tint of
   * the multi-Bereich org chart and is {@code null} for every other kind (Squadron / SK /
   * Organisationsleitung) and for a Bereich an admin has not yet assigned a department to. Nullable
   * so the column is purely additive (V166) and the chart degrades to an untinted tree until a
   * department is set. Stored as a string ({@link EnumType#STRING}) so the value reads the same
   * across Flyway, JPA and the wire DTOs.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "department", length = 32)
  private Department department;

  /**
   * Parent org unit in the Kartell hierarchy (epic #692, REQ-ORG-014, ADR-0025): the {@link
   * Bereich} that owns this Staffel/SK, the {@link Organisationsleitung} that owns this Bereich, or
   * {@code null}. The hierarchy is fixed at three levels (OL &gt; Bereich &gt; Staffel/SK), so the
   * parent's {@link #getKind()} is constrained by this row's kind — enforced at the data layer by
   * the {@code validate_org_unit_parent} trigger and the {@code chk_org_unit_ol_has_no_parent}
   * CHECK (V164), not at the JPA layer. A {@code null} parent is the additive-soak default; the
   * scope cascade treats it as "no ancestor expansion", so the system behaves exactly as the flat
   * two-kind model until an admin wires the hierarchy up. Lazy-fetched and excluded from {@code
   * toString} so rendering a row never walks the parent chain.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "parent_org_unit_id")
  @ToString.Exclude
  private OrgUnit parent;

  /**
   * Returns the concrete {@link OrgUnitKind} this row represents. Each concrete subclass overrides
   * this with a constant value matching its {@code @DiscriminatorValue}. The discriminator column
   * itself is read-only at the JPA layer (Hibernate manages it via the inheritance metadata), so
   * application code reaches for this method instead of trying to read the {@code kind} column
   * directly.
   *
   * @return the discriminator kind for this concrete row, never {@code null}.
   */
  public abstract OrgUnitKind getKind();
}
