/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.DiscriminatorType;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Abstract single-table base entity of the {@code org_unit} table, discriminated by {@link
 * OrgUnitKind} on the {@code kind} column; concrete kinds are {@link Squadron}, {@link
 * SpecialCommand}, {@link Bereich} and {@link Organisationsleitung} (ADR-0025).
 *
 * <p>A database CHECK constraint forces {@link #isPromotionEnabled} to {@code false} on every
 * non-squadron row.
 */
@Entity
@Table(name = "org_unit")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "kind", discriminatorType = DiscriminatorType.STRING, length = 32)
@Getter
@Setter
@ToString
@NoArgsConstructor
public abstract class OrgUnit extends AbstractEntity<UUID> {

  /**
   * Primary key, generated by Hibernate as a random UUID for new rows. The annotation also
   * overrides the {@link AbstractEntity#getId()} getter so {@link
   * org.springframework.data.domain.Persistable#getId()} resolves to the typed UUID field rather
   * than the erased base-class accessor.
   */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * Human-readable display name. Unique across all kinds (so a Spezialkommando cannot be named
   * "IRIDIUM" while the IRIDIUM squadron also exists), matching the {@code UNIQUE} constraint
   * inherited from the original {@code squadron} schema and preserved by V94.
   */
  @Column(unique = true, nullable = false)
  private String name;

  /**
   * Short identifier (3-5 letters) used in badges, chips, and audit logs. Unique across all kinds
   * for the same reasons as {@link #name}.
   */
  @Column(unique = true, nullable = false)
  private String shorthand;

  /** Free-text description shown on admin pages. May be {@code null} for newly-created rows. */
  @Column(columnDefinition = "TEXT")
  private String description;

  /**
   * Soft-delete flag. {@code false} hides the org unit from list views without deleting any data.
   * Defaults to {@code true} so a freshly-constructed entity goes straight into active state — the
   * existing {@code SquadronService.deleteSquadron} flow flips this rather than emitting a DELETE,
   * and {@link SpecialCommand} mirrors that behaviour.
   */
  @Column(nullable = false)
  private boolean active = true;

  /**
   * Whether the promotion subsystem is exposed to non-admin members of this org unit. Defaults to
   * {@code true}; forced to {@code false} on every non-squadron row by a database CHECK constraint.
   */
  @Column(name = "is_promotion_enabled", nullable = false)
  private boolean isPromotionEnabled = true;

  /**
   * Whether this org unit may be picked as the responsible (processing) org unit of a job order.
   * Defaults to {@code false} and is toggled only through the dedicated {@code profit-eligible}
   * endpoints, never by a regular update.
   */
  @Column(name = "is_profit_eligible", nullable = false)
  private boolean isProfitEligible = false;

  /**
   * The Kartell department of a {@link Bereich}, driving its colour tint in the org chart
   * (REQ-ORG-026). {@code null} for every other kind and for a Bereich without an assigned
   * department.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "department", length = 32)
  private Department department;

  /**
   * Parent org unit in the three-level hierarchy OL &gt; Bereich &gt; Staffel/SK (REQ-ORG-014), or
   * {@code null}. Parent-kind rules are enforced by the database; a {@code null} parent means no
   * ancestor expansion in the scope cascade.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "parent_org_unit_id")
  @ToString.Exclude
  private OrgUnit parent;

  /**
   * Returns the concrete {@link OrgUnitKind} of this row, matching its {@code @DiscriminatorValue}.
   *
   * @return the discriminator kind; never {@code null}.
   */
  public abstract OrgUnitKind getKind();
}
