plugins {
  id("idea")
  // `base` gives the root project the `check` lifecycle task that Spotless's
  // `isEnforceCheck` hooks `spotlessCheck` into (see the root Spotless block).
  id("base")
  alias(libs.plugins.owasp.dependencycheck)
  // Pulled in with `apply false` so the PitestPluginExtension type is on the
  // root build script's classpath for the `subprojects { plugins.withId(...) }`
  // configuration block below. Each subproject still applies the plugin itself.
  // Version comes from the `gradle/libs.versions.toml` catalog (single source of truth).
  alias(libs.plugins.pitest) apply false
  // Applied at the root (NOT `apply false`) so the root project gets its own
  // Spotless instance for the repo-wide non-Java formats configured below. The
  // type stays on the classpath for the strongly-typed `subprojects {}` block,
  // which configures the per-module Java formatting. Applying via the plugins DSL
  // (rather than an imperative `apply(...)` in the script body) keeps task
  // registration in the right phase under `--configure-on-demand`.
  alias(libs.plugins.spotless)
}

allprojects {
  group = "de.greluc.krt.profit.basetool"
  version = "0.0.1-SNAPSHOT"

  repositories { mavenCentral() }
}

// ---------------------------------------------------------------------------
// Root-level Spotless — formats the non-Java file types that NO other linter in
// this repo already covers: the Gradle Kotlin DSL, JSON, YAML, Markdown and the
// `.properties` bundles. Java stays configured per-subproject below
// (google-java-format + GPLv3 header); HTML / CSS / JS keep their dedicated Node
// linters in the frontend module (HTMLHint / Stylelint / ESLint). Applied at the
// ROOT (the subproject blocks below cannot reach the root build scripts or the
// repo-wide docs), with `base` so `spotlessCheck` is wired into `./gradlew check`.
//
// Deliberately NOT covered because formatting would be harmful or pointless:
//   - Flyway migrations (there is no `sql { }` block): reformatting changes the
//     migration checksum Flyway validates against -> schema-validation failure.
//   - Generated artifacts: the backend and ingest `openapi.json` (each regenerated
//     by its module's OpenApiGeneratorTest) and the CycloneDX SBOMs.
//   - `CHANGELOG.md`: the release workflow parses the `[Unreleased]` section, so
//     a reflow could break it.
//   - Vendored / build output: `node_modules`, `.gradle`, `build`, `.claude`.
//   - Tool-managed: `versions.properties` (refreshVersions), the Gradle wrapper.
//
// YAML and `.properties` get whitespace/newline hygiene ONLY (not a parse-and-
// re-serialise) so heavily-commented YAML (workflows, `application.yml`,
// compose) keeps its comments and the i18n bundles keep any intentional trailing
// space and their `\uXXXX` escapes.
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
  isEnforceCheck = true
  val vendored =
    arrayOf("**/build/**", "**/.gradle/**", "**/node_modules/**", "**/.claude/**", "**/.git/**")

  kotlinGradle {
    target("**/*.gradle.kts")
    targetExclude(*vendored)
    // ktfmt (Google style = 2-space, matching the root build script) is a pure
    // formatter, so `spotlessApply` output always satisfies `spotlessCheck` — no
    // unfixable lint rule can wedge CI the way ktlint's max-line-length would on
    // these long-comment build scripts.
    ktfmt().googleStyle()
  }

  json {
    target("**/*.json")
    targetExclude(
      *vendored,
      // Test/e2e fixtures may be asserted verbatim — never reflow them.
      "**/src/test/**",
      "**/src/e2e/**",
      // Generated by the per-module OpenApiGeneratorTest; hand-formatting fights the generator.
      "backend/src/main/resources/api/openapi.json",
      "ingest/src/main/resources/api/openapi.json",
      // CycloneDX SBOMs (auto-generated, churn on every build).
      "**/docs/*-bom.json",
      // npm-managed.
      "**/package.json",
      "**/package-lock.json",
      // Local, git-ignored tooling config.
      "**/*.local.json",
    )
    gson().indentWithSpaces(2)
  }

  format("yaml") {
    target("**/*.yml", "**/*.yaml")
    targetExclude(*vendored)
    trimTrailingWhitespace()
    endWithNewline()
  }

  // Markdown reflow via Spotless's built-in `flexmark` extension. NB: this MUST be
  // the built-in extension, not a custom `format("markdown") { flexmark {} }` — the
  // latter registers its task lazily and trips Gradle 9.5.1's mutation guard
  // ("DefaultTaskContainer#register ... cannot be executed in the current
  // context"), whereas the built-in extension registers eagerly during apply.
  // CHANGELOG.md is excluded (the release workflow parses its structure);
  // CHANGELOG-ARCHIVE.md holds the same very-long-line release entries split out
  // of it and is excluded for the same reason (keep the historical text stable).
  flexmark {
    // LICENSE.md is excluded because flexmark cannot converge on it (its output is
    // not idempotent), which it otherwise skips with a warning on every run.
    // CLAUDE.md is excluded because it is a hand-maintained agent-instruction file
    // whose deliberate structure must not be reflowed; it is also the file editors
    // most often re-save as CRLF on Windows, and with `core.autocrlf=true` +
    // `*.md text eol=lf` (.gitattributes) that CRLF working-tree copy reads as clean
    // to git until flexmark rewrites it to LF — flipping it to "modified" with an
    // empty `git diff` on every `spotlessApply`. Excluding it stops that churn.
    target("**/*.md")
    targetExclude(*vendored, "CHANGELOG.md", "CHANGELOG-ARCHIVE.md", "LICENSE.md", "CLAUDE.md")
    flexmark()
  }

  format("properties") {
    target("**/*.properties")
    // No trimTrailingWhitespace(): an i18n value may legitimately end in a space.
    targetExclude(*vendored, "versions.properties", "**/gradle-wrapper.properties")
    endWithNewline()
  }
}

// Shared Java conventions for the backend and frontend modules. Both subprojects
// apply the Spring Boot plugin and need an identical Test/BootRun/JavaCompile
// setup — centralising it here removes the previous duplication while still
// letting each module add its own specifics (frontend wires
// `finalizedBy(tasks.jacocoTestReport)` separately, for example).
subprojects {
  plugins.withId("java") {
    tasks.withType<Test>().configureEach {
      useJUnitPlatform()
      jvmArgs("--enable-native-access=ALL-UNNAMED")
      // Test heap, PER MODULE. Every @SpringBootTest spins its own ApplicationContext, so the
      // backend suite blows past the JVM 512 MiB default with a Java heap-space OOM at ~250 tests
      // in. History: 512m -> 1.5 GiB -> 2 GiB when the monitoring-instrumentation contexts (#936)
      // and the Mission/JobOrder service-split test classes (#948/#949) landed together -> 3 GiB
      // when the logging-audit suite added 71 backend test methods and the contexts tipped over
      // again (an OOM inside a bean creation, surfacing as "failed to load ApplicationContext" on
      // whichever @SpringBootTest happened to run at the moment the heap ran out).
      //
      // This is a per-module map rather than one shared number BECAUSE the total is what actually
      // binds. `org.gradle.parallel=true` plus a single `./gradlew build` in CI lets the module
      // test JVMs run CONCURRENTLY, so a uniform bump multiplies by three: 3 x 3 GiB alongside the
      // 2 GiB Gradle daemon would oversubscribe the 7 GiB github-hosted runner and trade a JVM heap
      // error for an OS-level kill, which is far harder to read. Giving the backend what it needs
      // and handing back what the small ingest suite never used keeps the concurrent peak at the
      // 6 GiB it already was. Re-derive this when a module's suite grows, and check the SUM.
      maxHeapSize =
        mapOf("backend" to "3072m", "frontend" to "2048m", "ingest" to "1024m")[project.name]
          ?: "1024m"
      systemProperty("spring.profiles.active", "test")
      // Mockito 5+ on JDK 24+ insists on running as a Java agent. Attach it via
      // -javaagent so the inline mock-maker can self-attach; -Xshare:off avoids
      // the AppCDS warning under the Spring Boot DevTools class loader.
      val mockitoCore = classpath.find { it.name.contains("mockito-core") }
      if (mockitoCore != null) {
        jvmArgs("-Xshare:off", "-javaagent:${mockitoCore.absolutePath}")
      }
      // Deliberately NOT setting `maxParallelForks > 1` here even though the
      // M-1 audit recommended it. A trial run with (cores / 2) destabilised
      // `WebClientResilienceTest.timeLimiter_ShouldTimeoutSlowResponses` — the
      // test asserts that a slow upstream times out within ~2 s, and under
      // forked CPU contention the JVM scheduler delay alone ate the budget.
      // Cross-module parallel (`org.gradle.parallel=true` in gradle.properties)
      // already runs backend and frontend test tasks concurrently, which is
      // most of the win for a 2-module build; revisit per-module forking once
      // the timing-sensitive resilience tests get refactored onto virtual time
      // (e.g. StepVerifier.withVirtualTime) so they no longer race against
      // wall-clock GC pauses.
    }

    tasks.withType<JavaCompile>().configureEach {
      options.encoding = "UTF-8"
      options.compilerArgs.addAll(listOf("-parameters", "-Xlint:unchecked", "-Xlint:deprecation"))
    }
  }

  // BootRun comes from the Spring Boot plugin. We avoid a hard reference to the
  // BootRun class (which would require this script to have the Spring Boot
  // plugin on its classpath) by configuring through `JavaExec` — BootRun is a
  // JavaExec subclass, so jvmArgs/systemProperty are available.
  plugins.withId("org.springframework.boot") {
    tasks.named<JavaExec>("bootRun") {
      jvmArgs("--enable-native-access=ALL-UNNAMED")
      systemProperty("spring.profiles.active", "dev")
    }

    // Security override for a Spring-Boot-BOM-managed transitive. The Boot 4.1.1 BOM pins the
    // embedded Tomcat to 11.0.24, and the Tomcat 11.0.25 advisory (2026-08-25) puts TEN CVEs on
    // that version, nine of them at or above the `failBuildOnCVSS = 7.0` gate below: CVE-2026-65637
    // (9.8, input validation — the incomplete-fix follow-up to CVE-2026-32990), CVE-2026-65905
    // (9.8, DIGEST authenticator capture-replay), CVE-2026-65182 (9.1, security-constraint bypass
    // when a longer path is declared before a more restrictive sub-path), CVE-2026-68525 (9.1, FORM
    // auth bypassing a method-specific constraint), CVE-2026-65183 (8.1, unix-domain-socket
    // TOCTOU),
    // CVE-2026-66422 (8.1, `security-role-ref` used as a Realm role alias), CVE-2026-68569 (8.1,
    // DataSourceRealm principal lookup failing open under CLIENT-CERT/SPNEGO), CVE-2026-65927 (7.5,
    // rewrite `[N]` off-by-one) and CVE-2026-68763 (7.5, HTTP/2 reset-stream allocation leak); plus
    // the sub-gate CVE-2026-73180 (6.8) and CVE-2026-66299 (WebSocket chat example). All ten are
    // fixed in 11.0.25, which is the latest 11.0.x on Maven Central and stays on the line the Boot
    // 4.1 BOM expects, so no 11.1.x jump. Boot has no 4.1.2 to bump to — 4.1.1 is the current
    // stable and 4.2.0-M1 is a milestone — so the override is the only path. Tomcat is on the
    // backend, frontend AND ingest runtime classpaths (embedded servlet container), so this is a
    // shipped-code exposure, not a build-time one, and it is fixed by upgrading rather than
    // suppressed. Discovered by the weekly scheduled scan, run 33392506709.
    //
    // Overriding the Boot BOM property is the conflict-free mechanism: it belongs right HERE (NOT
    // in gradle.properties, whose value is loaded first and would be silently overridden, and not
    // as a plain Gradle constraint), because io.spring.dependency-management emits every managed
    // version as a `{strictly ...}` constraint, so a competing constraint collides instead of
    // winning. Remove once the Boot BOM ships >= 11.0.25; the OWASP `dependencyCheckAggregate` gate
    // keeps the presence and the absence of the override honest either way.
    //
    // This block previously carried two further overrides — PostgreSQL 42.7.13 (CVE-2026-54291
    // SCRAM channel-binding downgrade) and Netty 4.2.17.Final (CVE-2026-56820 OCSP CertificateID,
    // CVE-2026-56819 HTTP/2 leak, CVE-2026-55833 SPDY decode DoS) — dropped with the 4.1.0 ->
    // 4.1.1 bump because the 4.1.1 BOM manages exactly those versions itself. It still does, so
    // they stay gone; only Tomcat needs pinning again.
    extra["tomcat.version"] = "11.0.25"
  }

  // JaCoCo coverage. Both modules want the same setup: emit XML + CSV + HTML
  // reports after every test run so CI / SonarQube / IDEs can consume the
  // data without re-running tests. Each subproject that opts in via
  // `plugins { jacoco }` automatically picks up this configuration.
  plugins.withId("jacoco") {
    tasks.withType<Test>().configureEach { finalizedBy(tasks.named("jacocoTestReport")) }

    // Generated / untestable code excluded from BOTH the coverage report and
    // the coverage gate so the ratio reflects hand-written logic only:
    //  - MapStruct *MapperImpl: its `@Generated` is
    //    `javax.annotation.processing.Generated` (SOURCE retention), invisible
    //    to JaCoCo's bytecode-time annotation filter, so it must be removed by
    //    class pattern. The `*Mapper` interface is NOT excluded — it carries
    //    default methods / comparators / `computeProfit(...)` that we test.
    //  - The one-line Spring Boot `*Application` `SpringApplication.run(...)`
    //    stub, which has no meaningful unit test.
    // (Lombok-generated members are auto-excluded because lombok.config sets
    // `lombok.addLombokGeneratedAnnotation = true`, and JaCoCo 0.8.2+ skips any
    // CLASS/RUNTIME `@Generated`.)
    val generatedClassExcludes =
      listOf("**/*MapperImpl.class", "**/*MapperImpl\$*.class", "**/*Application.class")
    fun filterGenerated(classes: FileCollection): FileCollection =
      files(classes.files.map { dir -> fileTree(dir) { exclude(generatedClassExcludes) } })

    tasks.named<JacocoReport>("jacocoTestReport") {
      // L-1: only generate the JaCoCo report when actually running in CI.
      // Locally a developer running `./gradlew :backend:test` from the IDE pays
      // the JaCoCo instrumentation overhead twice (test-runtime + the report
      // task) for output nobody looks at — Codecov / SonarQube only consume it
      // from CI runs. The `CI` env var is set by GitHub Actions by default,
      // GitLab CI, CircleCI, Drone and every other major runner; setting it
      // locally via `CI=true ./gradlew test` opts in explicitly when needed.
      onlyIf { System.getenv("CI") != null }
      reports {
        xml.required.set(true)
        csv.required.set(true)
        html.required.set(true)
      }
      classDirectories.setFrom(filterGenerated(classDirectories))
    }

    // Coverage ratchet, wired into `check`. A module-specific floor (set a few
    // points below the measured baseline — backend ~87% instr / ~71% branch,
    // frontend ~65% / ~52%, ingest ~98% / ~93%) fails the build on a real
    // coverage regression without flapping on small fluctuations. Tighten these
    // minimums upward over time. Uses the same generated-code excludes as the
    // report so the denominator matches; runs on the test exec data that `check`
    // already produces (so no extra test run). Unlike the report it is NOT gated
    // on `CI`, so a regression fails fast on a local `./gradlew check` too.
    // `ingest` sits far above the other two because the gateway is small and
    // almost entirely branch logic (filters, relay, problem mapping) — the
    // generic 0.50/0.40 fallback it used before was no gate at all there.
    val instructionFloor =
      mapOf("backend" to "0.82", "frontend" to "0.60", "ingest" to "0.93")[project.name] ?: "0.50"
    val branchFloor =
      mapOf("backend" to "0.65", "frontend" to "0.46", "ingest" to "0.85")[project.name] ?: "0.40"
    tasks.named<JacocoCoverageVerification>("jacocoTestCoverageVerification") {
      dependsOn(tasks.named("test"))
      classDirectories.setFrom(filterGenerated(classDirectories))
      violationRules {
        rule {
          element = "BUNDLE"
          limit {
            counter = "INSTRUCTION"
            value = "COVEREDRATIO"
            minimum = instructionFloor.toBigDecimal()
          }
          limit {
            counter = "BRANCH"
            value = "COVEREDRATIO"
            minimum = branchFloor.toBigDecimal()
          }
        }
      }
    }
    tasks.named("check").configure { dependsOn(tasks.named("jacocoTestCoverageVerification")) }
  }

  // Pitest mutation testing (info.solidsoft.pitest). Runs on demand via
  // `./gradlew :<module>:pitest` — intentionally NOT wired into `check`
  // because a full mutation run takes O(minutes) per service and is far too
  // slow for the standard PR-build path. Scope defaults to the business-logic
  // service layer (`...basetool.<module>.service.*`); DTOs, mappers,
  // repositories and config classes are excluded because mutating them rarely
  // catches real test-suite gaps. Reports land under
  // `<module>/build/reports/pitest/index.html`.
  //
  // Tuning notes:
  // - `threads = 4` keeps a single-developer laptop responsive while still
  //   parallelising mutation runs across test classes.
  // - JVM args mirror the regular Test task (`--enable-native-access` plus
  //   `-Xshare:off -javaagent:<mockito-core>` so Mockito 5+ self-attaches in
  //   PIT's isolated minion processes; without that the green-suite
  //   prerequisite fails before any mutation is generated).
  // - The first invocation will almost certainly fail because some service
  //   tests rely on a Spring context that PIT's minion process does not
  //   start; the team should add the affected test classes to
  //   `excludedTestClasses` (or move them to `*IntegrationTest` naming) as a
  //   follow-up, then tighten `mutationThreshold` / `coverageThreshold` to
  //   make the gate strict.
  plugins.withId("info.solidsoft.pitest") {
    extensions.configure<info.solidsoft.gradle.pitest.PitestPluginExtension>("pitest") {
      junit5PluginVersion.set(libs.versions.pitestJunit5.get())
      targetClasses.set(listOf("de.greluc.krt.profit.basetool.${project.name}.service.*"))
      targetTests.set(listOf("de.greluc.krt.profit.basetool.${project.name}.service.*Test"))
      threads.set(4)
      outputFormats.set(listOf("HTML", "XML"))
      timestampedReports.set(false)

      // Build the same JVM-arg list the regular Test task uses, so Mockito 5+
      // can self-attach as a Java agent inside PIT's isolated minions and the
      // native-access warning is silenced. The mockito-core path is resolved
      // lazily from the test runtime classpath.
      val testClasspath = configurations.getByName("testRuntimeClasspath")
      jvmArgs.set(
        provider {
          val args = mutableListOf("--enable-native-access=ALL-UNNAMED")
          val mockitoCore = testClasspath.files.find { it.name.contains("mockito-core") }
          if (mockitoCore != null) {
            args += "-Xshare:off"
            args += "-javaagent:${mockitoCore.absolutePath}"
          }
          args
        }
      )
    }
  }

  // Checkstyle (Gradle core plugin). Uses the Google Java Style config
  // (`config/checkstyle/google_checks.xml`, downloaded from the Checkstyle
  // 13.6.0 release tag) which enforces 2-space indents, 100-char lines,
  // Google-style imports, naming conventions, Javadoc on public API, etc.
  //
  // Phase 4 (this configuration): the gate is now STRICT.
  // `ignoreFailures = false` + `maxWarnings = 0` mean any new Checkstyle
  // warning or error fails `./gradlew check` — regressions are caught at
  // CI / PR time instead of accumulating silently. Reports land under
  // `<subproject>/build/reports/checkstyle/{main,test}.html`. The test
  // source set scan is disabled — test code intentionally uses different
  // conventions (long method names with underscores, longer lines for
  // BDD-style assertions) that Google's style flags as noise.
  plugins.withId("checkstyle") {
    extensions.configure<CheckstyleExtension>("checkstyle") {
      toolVersion = libs.versions.checkstyle.get()
      configFile = rootProject.file("config/checkstyle/google_checks.xml")
      isIgnoreFailures = false
      maxWarnings = 0
    }
    tasks.matching { it.name == "checkstyleTest" }.configureEach { enabled = false }
  }

  // Spotless (com.diffplug.spotless). Auto-formats Java sources with
  // google-java-format — same 2-space indent / 100-char width / Google import
  // order that `config/checkstyle/google_checks.xml` enforces. Applying
  // Spotless therefore resolves the bulk of Checkstyle's Indentation,
  // LineLength, CustomImportOrder, AvoidStarImport, EmptyLineSeparator,
  // OperatorWrap and WhitespaceAround warnings in a single pass.
  //
  // Phase 4 (this configuration): `enforceCheck = true` wires `spotlessCheck`
  // into `./gradlew check` so any unformatted file fails the build. Run
  // `./gradlew spotlessApply` locally before pushing to auto-fix; CI then
  // re-runs `spotlessCheck` to verify the diff is clean.
  plugins.withId("com.diffplug.spotless") {
    extensions.configure<com.diffplug.gradle.spotless.SpotlessExtension>("spotless") {
      isEnforceCheck = true
      java {
        // google-java-format is pinned to a version that supports JDK 25.
        // Older google-java-format (the default bundled by earlier Spotless
        // releases) reflects against
        // `com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()` —
        // the return type of that method changed in JDK 25 (Queue -> Deque) and the
        // reflection lookup explodes with `NoSuchMethodError`. CI runs JDK 25 Temurin
        // (see `.github/workflows/ci.yml`), so without an explicit pin the spotless
        // task fails 767 files with `google-java-format(java.lang.NoSuchMethodError)`.
        // The catalog pins a JDK-25-compatible google-java-format (>= 1.35.0).
        googleJavaFormat(libs.versions.googleJavaFormat.get()).reflowLongStrings()
        removeUnusedImports()
        // GPLv3 file header, enforced on every Java source (main + test + e2e).
        // The project is GPL-3.0-only (LICENSE.md is the GPLv3 text); the SPDX
        // tag makes that machine-readable. Fixed year (no `$YEAR` token) so
        // `spotlessCheck` never churns the header across calendar years. Run
        // `./gradlew spotlessApply` to (re)stamp.
        licenseHeader(
          """
          /*
           * Profit Basetool - squadron-management web app.
           * Copyright (C) 2026 Lucas Greuloch
           *
           * SPDX-License-Identifier: GPL-3.0-only
           *
           * This program is free software: you can redistribute it and/or modify
           * it under the terms of the GNU General Public License as published by
           * the Free Software Foundation, version 3.
           *
           * This program is distributed in the hope that it will be useful,
           * but WITHOUT ANY WARRANTY; without even the implied warranty of
           * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
           * GNU General Public License for more details.
           *
           * You should have received a copy of the GNU General Public License
           * along with this program.  If not, see <https://www.gnu.org/licenses/>.
           */

          """
            .trimIndent() + "\n"
        )
      }
    }
  }

  // CycloneDX SBOM generation is a RELEASE-ONLY concern, deliberately kept out of
  // the everyday build. The cyclonedx-gradle plugin (3.x) wires each SBOM output
  // file as an artifact `builtBy(cyclonedxDirectBom)`, which pulls the task into
  // `assemble` (hence `build`); out of the box a plain `./gradlew build` therefore
  // regenerates the committed `<module>/docs/*-bom.*` on every run and churns the
  // working tree for output nobody consumes outside a release. The SBOMs are
  // produced only by the release-prepare workflow (which commits the refreshed
  // copies) and on demand via `./gradlew :<module>:cyclonedxBom`. So gate both
  // tasks on whether a cyclonedx task was explicitly named on the command line:
  // when it was not, `enabled = false` makes them SKIP — a disabled task never
  // runs its action, so an ordinary build leaves the committed SBOMs untouched —
  // while an explicit `cyclonedxBom` / `cyclonedxDirectBom` invocation (release or
  // manual) re-enables them. `enabled` has a single writer here, so the guarantee
  // holds regardless of plugin/Gradle configuration order.
  plugins.withId("org.cyclonedx.bom") {
    val sbomExplicitlyRequested =
      gradle.startParameter.taskNames.any { it.substringAfterLast(':').startsWith("cyclonedx") }
    tasks.named("cyclonedxDirectBom").configure { enabled = sbomExplicitlyRequested }
    tasks.named("cyclonedxBom").configure { enabled = sbomExplicitlyRequested }
  }
}

// ---------------------------------------------------------------------------
// Terms-of-Use version, derived from the text itself (REQ-SEC-028).
//
// The acceptance gate must re-prompt whenever the terms CHANGE, and the only way
// that cannot go stale is to derive the version from the wording rather than from
// a number someone remembers to bump. So: hash every `terms.*` entry of the German
// bundle (the authoritative wording) and use the digest as the version.
//
// The result is COMMITTED to `backend/src/main/resources/terms-version.properties`
// rather than generated into the build directory, and this task is deliberately NOT
// wired into `processResources`. Both follow the `openapi.json` precedent in this
// repo, and both exist because of a real failure: generating it at build time made
// the BACKEND build read a FRONTEND source file, and the backend Docker image copies
// only `frontend/build.gradle.kts` (for layer caching) — so the image build died with
// "Input file does not exist" while every local build was green. A committed artifact
// needs no cross-module build-time dependency at all.
//
// Drift is caught by `TermsVersionParityTest`, which re-derives the digest from the
// bundle and fails the build when the committed file disagrees. Regenerate with:
//     ./gradlew generateTermsVersion
//
// `terms.last_updated` is deliberately INSIDE the hash: the date is part of the
// document, and bumping it is itself an announcement that the terms changed.
tasks.register("generateTermsVersion") {
  description = "Regenerates the committed Terms-of-Use version from the German message bundle."
  // Backend-owned since the document became an API resource: the digest has to hash the text
  // that is actually SERVED. Left pointing at the frontend it would have kept hashing a bundle
  // no longer carrying the terms, producing a stable version for wording that had changed --
  // a gate that never re-prompts, with nothing to show it had stopped working.
  val bundle = rootProject.file("backend/src/main/resources/messages_de.properties")
  val target = rootProject.file("backend/src/main/resources/terms-version.properties")
  // The escape hatch for a purely cosmetic edit (a typo, a reflow): pinning the
  // version leaves every existing acceptance valid instead of re-prompting the
  // whole squadron — which, with the gate also covering ingest, would otherwise
  // stop the desktop extractor for everyone until they log into the web UI.
  val override = (project.findProperty("termsVersion") as String?)?.takeIf { it.isNotBlank() }
  outputs.upToDateWhen { false }
  doLast {
    val version = override ?: termsVersionDigest(bundle)
    target.parentFile.mkdirs()
    // A literal LF, not System.lineSeparator(): Spotless normalises .properties to LF, so a CRLF
    // written here leaves every Windows run of this task with a red spotlessPropertiesCheck for a
    // file whose CONTENT is correct — a "format violation" reported against the one artifact
    // nobody edits by hand, and the build's only hint is to run a 25-minute spotlessApply.
    target.writeText("basetool.terms.version=" + version + "\n", Charsets.UTF_8)
    logger.lifecycle("Terms-of-Use version: $version -> ${target.relativeTo(rootDir)}")
  }
}

// OWASP Dependency-Check (org.owasp.dependencycheck) 13.0.0. Aggregates over
// all subprojects via `./gradlew dependencyCheckAggregate`. CVSS gate now fails
// the build on findings with CVSS 7.0 or higher (audit finding L-8: previously
// the gate was wide open at CVSS 11 — triage-only). 7.0 covers the OWASP "HIGH"
// severity band; CRITICAL (>= 9.0) is included by definition. The plugin's
// first invocation downloads the NVD feed (~500 MB cached under
// `~/.gradle/dependency-check-data`) and takes 5-15 minutes; subsequent runs
// are seconds. Set `-PnvdApiKey=<key>` (CI: `NVD_API_KEY` repo secret) to
// bypass the public NVD rate limit — register a free key at
// https://nvd.nist.gov/developers/request-an-api-key.
dependencyCheck {
  failBuildOnCVSS = 7.0f
  formats = listOf("HTML", "SARIF")
  outputDirectory.set(layout.buildDirectory.dir("reports/dependency-check"))
  // Suppression file for findings that are either CPE confusion (the NVD
  // matcher attributes a CVE to a different product that shares a token with
  // ours) or sit on a build-time-only classpath that never reaches the
  // deployed Spring Boot fat JAR. Each entry carries a `<notes>` block
  // explaining the reason - real production CVEs are NEVER suppressed, they
  // are fixed by upgrading the dependency.
  suppressionFile = rootProject.file("config/owasp/dependency-check-suppressions.xml").absolutePath
  // Treat the on-disk NVD copy as valid for a full ISO-week. The
  // `.github/workflows/dependency-check.yml` actions/cache entry is keyed on
  // the ISO week as well and the weekly cron re-warms it, so within a week we
  // reuse the local DB and skip every NVD API call. Only the first run of
  // each week actually contacts the NVD endpoint, which is what keeps the
  // workflow inside the 5-req/30-s public rate limit when `NVD_API_KEY` is
  // unset. The plugin default of 4 hours forced an update on essentially
  // every invocation, which on github-hosted runners (shared IP pool with
  // every other CI job on github.com refreshing on Monday morning) led to
  // 429s mid-transaction and a corrupt H2 DB — see run 25933803540.
  // Bound every outbound HTTP call the engine makes. WITHOUT these the scan stalls indefinitely:
  // dependency-check queries NVD, the NPM Audit API, Maven Central, OSS Index and RetireJS, and a
  // socket that stops responding is simply waited on forever - then retried, up to the
  // `nvd.maxRetryCount` below. The task prints "Checking for updates and analyzing dependencies for
  // vulnerabilities" and NOTHING after it, so the run looks busy rather than stuck and only ends
  // when the CI job timeout kills it.
  //
  // That is what 24 runs between 2026-08-19 and 2026-09-04 were doing: 14 on `main`, 10 on feature
  // branches, all cancelled at the job ceiling with zero output. It is not a cold-cache cost - a
  // COLD run finishes in 8-14 minutes (run 31309086034 on `main`, 8m29s; run 33845554721 on a PR,
  // 13m48s) and a warm one in under a minute. Exactly one of the stalled runs died with a message
  // instead of hanging, and it names the mechanism: run 33847146815,
  // `DownloadFailedException: ... 'https://registry.npmjs.org/-/npm/v1/security/audits';
  // Read timed out` -> `SocketTimeoutException`. That one connection happened to carry a timeout;
  // the rest do not.
  //
  // With a read timeout the same stall surfaces as an error in minutes, the engine disables the
  // affected analyzer and continues, and the scan still reaches its SARIF upload - which is what
  // actually keeps the Security tab honest. 120s is deliberately generous: the NVD paging calls are
  // slow but they do respond, so this must not fire on a healthy sync.
  //
  // Kotlin DSL note: `connectionTimeout = ...` does NOT compile. Both setters are overloaded
  // (Object / Number / Duration) and Kotlin cannot resolve the `=` assignment against them, failing
  // with "No applicable 'assign' function found for '=' overload". Call the setter explicitly.
  setConnectionTimeout(java.time.Duration.ofSeconds(30))
  setReadTimeout(java.time.Duration.ofSeconds(120))
  nvd.validForHours = 168
  // Bump retries above the default of 10 so a transient 429 burst does not
  // abort the in-progress H2 update; the corruption-on-abort failure mode
  // referenced above only triggers once retries are exhausted while writes
  // are pending.
  nvd.maxRetryCount = 20
  val resolvedNvdApiKey = (project.findProperty("nvdApiKey") as String?)?.takeIf { it.isNotBlank() }
  if (resolvedNvdApiKey != null) {
    nvd.apiKey = resolvedNvdApiKey
    // ~30 req/min, comfortably inside NVD's authenticated 50/30-s budget.
    nvd.delay = 2000
  } else {
    // Public NVD limit is 5 req/30 s; 16 s between calls keeps us at
    // ~3.75 req/30 s with headroom for runner-pool contention on the same
    // source IP. Register and configure an API key (see header comment) to
    // drop this delay and make the first-of-week run finish in minutes
    // instead of tens of minutes.
    nvd.delay = 16000
  }
}

/**
 * Derives the Terms-of-Use version from a message bundle: every `terms.*` entry, sorted, joined and
 * SHA-256'd, truncated to 16 hex characters. Kept as one function so the Gradle task and the parity
 * test cannot drift apart in how they compute it.
 */
fun termsVersionDigest(bundle: File): String {
  val clauses =
    bundle
      .readLines(Charsets.UTF_8)
      .filter { it.startsWith("terms.") && it.contains('=') }
      .sorted()
      .joinToString(separator = "\n")
  check(clauses.isNotEmpty()) { "No terms.* entries found in ${bundle.path}" }
  // A `.properties` value may be continued onto the next line with a trailing backslash, and such a
  // continuation line starts with neither `terms.` nor contains `=` — so the filter above would
  // skip it and editing that part of a clause would NOT change the version. That silently defeats
  // the one property this whole design exists for. No terms.* entry uses a continuation today, so
  // this guard is a tripwire for the day someone wraps a long clause, not a fix for a live bug.
  check(clauses.lines().none { it.endsWith("\\") }) {
    "A terms.* entry in ${bundle.path} uses a backslash line continuation. The digest only sees " +
      "the first line, so edits to the rest would not re-prompt anyone. Put the clause on one line."
  }
  return java.security.MessageDigest.getInstance("SHA-256")
    .digest(clauses.toByteArray(Charsets.UTF_8))
    .joinToString("") { "%02x".format(it) }
    .substring(0, 16)
}
