services:
  keycloak-dev:
    environment:
      KC_HOSTNAME: 127.0.0.1
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /auth
    ports: !override
      - "18080:18080"

  backend-dev:
    ports: !override
      - "11261:11261"
    environment:
      KEYCLOAK_ISSUER_URI: http://127.0.0.1:18080/auth/realms/iri
      KEYCLOAK_JWK_SET_URI: http://keycloak:18080/auth/realms/iri/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:18080/auth/realms/iri/protocol/openid-connect/certs
