services:
  keycloak-dev:
    environment:
      KC_HOSTNAME: host.docker.internal
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}

  backend-dev:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SSL_KEY_STORE_PASSWORD: basetool-test
      APP_NOTIFICATIONS_REDIS_FANOUT_ENABLED: "false"
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:18080/auth/realms/iri
      KEYCLOAK_ADMIN_URL: http://keycloak:18080/auth
      KEYCLOAK_REALM: iri
      KEYCLOAK_ADMIN_CLIENT_ID: backend-service
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    volumes: !override
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
      - ./docker/test-tls/basetool-test-backend.p12:/run/secrets/keystore.p12:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-dev:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SSL_KEY_STORE_PASSWORD: basetool-test
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:18080/auth/realms/iri
      REDIS_HOST: redis
      BACKEND_URL: https://backend:11261
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes: !override
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
      - ./docker/test-tls/basetool-test-frontend.p12:/run/secrets/keystore.p12:ro

  ingest-dev:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SSL_KEY_STORE_PASSWORD: basetool-test
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:18080/auth/realms/iri
      FRONTEND_URL: http://localhost:18081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: !override
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
      - ./docker/test-tls/basetool-test-ingest.p12:/run/secrets/keystore.p12:ro
