services:
  db-backend-dev:
    volumes: !override
      - iri-e2e-db-backend:/var/lib/postgresql/data
  db-keycloak-dev:
    volumes: !override
      - iri-e2e-db-keycloak:/var/lib/postgresql/data
  redis-dev:
    command: redis-server --save "" --appendonly no --notify-keyspace-events Egx --aclfile /etc/redis/users.acl
    volumes: !override
      - ./docker/test-redis/users.acl:/etc/redis/users.acl:ro
  keycloak-dev:
    command: start-dev --import-realm --cache=local
    environment:
      KC_HOSTNAME: http://host.docker.internal:18080/auth
    networks:
      net-backend-keycloak:
        aliases:
          - keycloak
          - host.docker.internal
    volumes: !override
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
  backend-dev:
    user: "0:0"
    environment:
      APP_RATE_LIMIT_ENABLED: "false"
      APP_REGISTRATION_REQUIRE_APPROVAL: "false"
    extra_hosts: !override []
    volumes: !override
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
      - ./docker/test-tls/basetool-test-backend.p12:/run/secrets/keystore.p12:ro
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
  frontend-dev:
    user: "0:0"
    environment:
      SERVER_HTTP2_ENABLED: "false"
      APP_SESSION_TYPE_ALLOW_LIST: enforce
    extra_hosts: !override []
    volumes: !override
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777
      - ./docker/test-tls/basetool-test-frontend.p12:/run/secrets/keystore.p12:ro
      - type: tmpfs
        target: /app/logs
        tmpfs:
          mode: 0o777

volumes:
  iri-e2e-db-backend:
  iri-e2e-db-keycloak:
