map $scheme $hsts_header {
  default "";
  https   "max-age=63072000;includeSubDomains; preload";
}

map $http_accept $maintenance_target {
    default                                /maintenance/maintenance.html;
    "~*application/(problem\+)?json"       /maintenance/maintenance.json;
}

map $remote_addr $krt_limit_key {
    default                                                  $remote_addr;
    "~*^(?<v6net>[0-9a-f]+:[0-9a-f]+:[0-9a-f]+:[0-9a-f]+):"  "$v6net::";
}
limit_req_zone  $krt_limit_key zone=krt_req_perip:10m rate=20r/s;
limit_conn_zone $krt_limit_key zone=krt_conn_perip:10m;
