FROM scratch

COPY docker-compose.yml /config/docker-compose.yml
COPY docker-compose.monitoring.yml /config/docker-compose.monitoring.yml
COPY docker/maintenance /config/docker/maintenance
COPY docker/edge /config/docker/edge
COPY docker/acme /config/docker/acme
COPY keycloak-theme /config/keycloak-theme
COPY monitoring /config/monitoring
COPY quadlet /config/quadlet
