test.maxHeap=4096m
coverage.instruction=0.82
coverage.branch=0.65
mutation.targetClasses=de.greluc.krt.profit.basetool.backend.service.*
mutation.targetTests=de.greluc.krt.profit.basetool.backend.service.*Test
