users:
  - name: sysadm
    groups: [wheel]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGaLCBXB4sF+5Qu2lpVh7K7clqvNQiS6QuKpdzIr6l6NmNuc9892vPhwFKdy0vuoh/kFtch4WNIh3fjzG+RGZ0I= lucas@LUCAS-DESKTOP

      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMQ9ZZFW/dkY6kMitzDdUqCDD5F0dBQLuq8IX5IaaAVX basetool-ansible-wsl@LUCAS-DESKTOP

disable_root: false

package_update: true
package_upgrade: true

power_state:
  mode: reboot
  condition: true
  message: "Rebooting into the updated kernel before provisioning"
