/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.domain.JavaMethod;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.AssertTrue;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.json.JsonMapper;

/**
 * Guards the committed {@code openapi.json} against the one defect that made it rewrite itself on
 * every build: {@link AssertTrue} cross-field validators leaking into the generated document as
 * schema properties.
 *
 * <p><b>Why this test exists.</b> springdoc derives schema properties from bean accessors, and a
 * Jakarta {@code @AssertTrue} guard looks exactly like a boolean getter. Two things then go wrong
 * at once. The harmless-looking one is a contract lie — {@code InventoryItemCreateDto} advertised
 * {@code catalogReferenceValid}, {@code missionFreeForGameItem} and {@code
 * qualityConsistentWithCatalog} as request fields although they are computed from {@code
 * materialId} / {@code gameItemId} / {@code quality} and are ignored on the wire; the frontend's
 * generated TypeScript types inherited all three. The expensive one is that accessors are harvested
 * in {@code Class#getDeclaredMethods()} order, which the JVM explicitly does not guarantee
 * (declared *fields* are stable in practice, methods are not). Those three properties therefore
 * permuted between JVM runs, so {@code ./gradlew check} rewrote the 1.8 MB spec on a tree with no
 * controller, DTO or mapper change at all. Measured on 2026-08-03: the ordering changed in 16 of 24
 * consecutive commits that touched the file, cycling through permutations unrelated to what each
 * commit did, and four regenerations from an identical tree produced three different orderings.
 *
 * <p>That churn is corrosive precisely because the repository treats the spec as a meaningful
 * signal: it is never hand-edited, it must track the controllers, and the PR template has a
 * checklist item for it. A file that dirties itself on every build trains reviewers to wave the
 * diff through.
 *
 * <p>The fix is {@code @Schema(hidden = true)} on each guard, which removes it from the document
 * without touching Jackson or Bean Validation. This test pins that at the source rather than
 * asserting on the generated bytes, so a newly added guard fails here — naming the method to
 * annotate — instead of silently reintroducing the churn months later.
 */
class OpenApiDerivedPropertyTest {

  /** Production bytecode of the backend module; test classes are excluded deliberately. */
  private static final JavaClasses CLASSES =
      new ClassFileImporter()
          .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
          .importPackages("de.greluc.krt.profit.basetool.backend");

  /** The committed spec, relative to the module directory tests run in. */
  private static final Path OPENAPI = Paths.get("src/main/resources/api/openapi.json");

  /**
   * Every {@code @AssertTrue} validator on a <em>published</em> type must be hidden from the
   * OpenAPI document.
   *
   * <p>Scoped to types that actually appear under {@code components.schemas}, which is exactly the
   * set that can churn: a guard on a {@code @ConfigurationProperties} class (e.g. {@code
   * DiscordSpiPrecheckProperties#isSharedSecretBlankOrStrong()}) never reaches springdoc, and
   * demanding a Swagger annotation there would be cargo cult. The scoping has no blind spot either
   * — a type absent from the document publishes no properties by definition.
   *
   * <p>Fails with the fully qualified method name and the exact annotation to add, because the
   * symptom otherwise shows up as an unrelated {@code openapi.json} diff in someone else's PR.
   *
   * @throws IOException if the committed spec cannot be read
   */
  @Test
  void everyAssertTrueValidatorOnAPublishedTypeIsHiddenFromTheOpenApiDocument() throws IOException {
    Set<String> publishedTypes = publishedSchemaNames();

    List<JavaMethod> validators =
        CLASSES.stream()
            .flatMap(javaClass -> javaClass.getMethods().stream())
            .filter(method -> method.isAnnotatedWith(AssertTrue.class))
            .filter(method -> publishedTypes.contains(method.getOwner().getSimpleName()))
            .sorted(java.util.Comparator.comparing(JavaMethod::getFullName))
            .toList();

    // A scan that silently matches nothing would let this test pass forever without checking
    // anything — which is precisely how the original churn survived unnoticed for months.
    assertFalse(
        validators.isEmpty(),
        "found no @AssertTrue validators on published types at all — the classpath scan or the"
            + " schema lookup is broken, not the code");

    List<String> exposed = new ArrayList<>();
    for (JavaMethod validator : validators) {
      Schema schema = validator.reflect().getAnnotation(Schema.class);
      if (schema == null || !schema.hidden()) {
        exposed.add(validator.getFullName());
      }
    }

    assertTrue(
        exposed.isEmpty(),
        () ->
            "These @AssertTrue validators are derived from other fields and are not part of any"
                + " request payload, but they would be published as schema properties — and"
                + " accessor order is not stable across JVM runs, so they rewrite openapi.json"
                + " between builds. Annotate each with @Schema(hidden = true):\n  "
                + String.join("\n  ", exposed));
  }

  /**
   * The committed spec itself carries no such property — the artifact-level backstop.
   *
   * <p>The rule above constrains the source; this one constrains the file that actually churned, so
   * a future springdoc upgrade that starts honouring {@code @Schema(hidden = true)} differently
   * cannot regress the artifact unnoticed.
   *
   * @throws IOException if the committed spec cannot be read
   */
  @Test
  void theCommittedSpecPublishesNoAssertTrueValidator() throws IOException {
    Set<String> derived =
        CLASSES.stream()
            .flatMap(javaClass -> javaClass.getMethods().stream())
            .filter(method -> method.isAnnotatedWith(AssertTrue.class))
            .map(method -> propertyNameOf(method.getName()))
            .collect(Collectors.toCollection(TreeSet::new));

    List<String> offenders = new ArrayList<>();
    schemas()
        .forEach(
            (name, schema) -> {
              Object properties = ((Map<?, ?>) schema).get("properties");
              if (properties instanceof Map<?, ?> propertyMap) {
                propertyMap.keySet().stream()
                    .map(String::valueOf)
                    .filter(derived::contains)
                    .forEach(property -> offenders.add(name + "." + property));
              }
            });

    assertTrue(
        offenders.isEmpty(),
        () ->
            "openapi.json publishes derived @AssertTrue validators as request properties;"
                + " regenerate the spec after hiding them:\n  "
                + String.join("\n  ", offenders));
  }

  /**
   * Reads {@code components.schemas} from the committed spec.
   *
   * <p>Reading is safe against a concurrent regeneration: {@code OpenApiGeneratorTest} moves a
   * fully-written temporary file into place, so a reader always sees one complete document.
   *
   * @return the schema map, keyed by schema name
   * @throws IOException if the committed spec cannot be read
   */
  private static Map<?, ?> schemas() throws IOException {
    Map<?, ?> document =
        JsonMapper.builder().build().readValue(Files.readString(OPENAPI), Map.class);
    return (Map<?, ?>) ((Map<?, ?>) document.get("components")).get("schemas");
  }

  /**
   * Names of every type published under {@code components.schemas}.
   *
   * @return the published schema names, which match the declaring types' simple names
   * @throws IOException if the committed spec cannot be read
   */
  private static Set<String> publishedSchemaNames() throws IOException {
    return schemas().keySet().stream().map(String::valueOf).collect(Collectors.toSet());
  }

  /**
   * Maps a boolean accessor name to the JavaBeans property name springdoc would publish, e.g.
   * {@code isSplitConfigConsistent} to {@code splitConfigConsistent}.
   *
   * <p>Only the {@code is} prefix is stripped: every {@code @AssertTrue} guard in this codebase is
   * a {@code boolean} accessor, and Bean Validation would reject a non-boolean one anyway.
   *
   * @param methodName the accessor's simple name
   * @return the published property name
   */
  private static String propertyNameOf(String methodName) {
    if (methodName.startsWith("is") && methodName.length() > 2) {
      String remainder = methodName.substring(2);
      return Character.toLowerCase(remainder.charAt(0)) + remainder.substring(1);
    }
    return methodName;
  }
}
