error_page 502 503 504 =503 @maintenance;

location @maintenance {
    internal;

    root /usr/share/nginx/html;
    rewrite ^.*$ $maintenance_target break;

    types {
        application/problem+json json;
        text/html                html;
    }

    add_header Retry-After   "60"       always;
    add_header Cache-Control "no-store" always;
}
