include /etc/nginx/edge/include/proxy-common.conf;

proxy_set_header X-Forwarded-For   $remote_addr;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header Forwarded         "";

include /etc/nginx/edge/include/upstream-tls.conf;
proxy_ssl_name                keycloak;
set $upstream_host keycloak;
proxy_pass https://$upstream_host:18443$request_uri;
