proxy_ssl_verify              on;
proxy_ssl_verify_depth        1;
proxy_ssl_trusted_certificate /etc/nginx/grafana-upstream.crt;
proxy_ssl_server_name         on;
proxy_ssl_name                grafana;
