test.maxHeap=1024m
coverage.instruction=0.93
coverage.branch=0.85
mutation.targetClasses=de.greluc.krt.profit.basetool.ingest.service.*
mutation.targetTests=de.greluc.krt.profit.basetool.ingest.service.*Test
