/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.frontend.oss;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

/**
 * Pins the licence notice of REQ-UI-021 at both ends: the grouping {@link OssLicenseCatalog} does,
 * and the report the build actually generates — the half a unit test with a hand-written file could
 * never catch going missing.
 */
@DisplayName("Open-source licence catalog")
class OssLicenseCatalogTest {

  /** The licences the root build's gate admits; the generated report must stay inside them. */
  private static final Set<String> GATE_ALLOWED =
      Set.of(
          "Apache-2.0",
          "BSD-2-Clause",
          "BSD-3-Clause",
          "CC0-1.0",
          "GPL-2.0-with-classpath-exception",
          "LGPL-2.1-only",
          "MIT",
          "MIT-0",
          "MPL-2.0");

  private final ObjectMapper mapper = JsonMapper.builder().build();

  @Test
  @DisplayName("the build generated a report for this classpath, and it is not empty")
  void theGeneratedReportIsOnTheClasspath() {
    OssLicenseCatalog catalog = new OssLicenseCatalog(mapper);

    assertThat(catalog.isAvailable())
        .as("oss/oss-licenses.json must be generated by :frontend:generateOssLicenses")
        .isTrue();
    assertThat(catalog.componentCount()).isGreaterThan(100);
    assertThat(catalog.generator()).startsWith("licensee ");
  }

  @Test
  @DisplayName("the report covers every shipped module, merged per component")
  void theReportMergesTheShippedModules() {
    List<OssComponent> components = components();

    OssComponent springCore = find(components, "org.springframework:spring-core");
    assertThat(springCore.modules()).contains("backend", "frontend", "ingest");
    assertThat(find(components, "org.flywaydb:flyway-core").modules()).containsExactly("backend");
    assertThat(find(components, "Lato").modules())
        .containsExactly("backend", "frontend", "keycloak-theme");
  }

  @Test
  @DisplayName("AspectJ does not ship: its EPL-2.0 has no GPL secondary licence (ADR-0197)")
  void aspectjDoesNotShip() {
    assertThat(components())
        .extracting(OssComponent::name)
        .noneMatch(name -> name.startsWith("org.aspectj:"))
        .doesNotContain("org.springframework:spring-aspects");
  }

  @Test
  @DisplayName("every library offers at least one licence the gate allows, named by SPDX id")
  void everyLibraryIsUnderAnAllowedSpdxLicence() {
    List<OssComponent> libraries =
        components().stream().filter(c -> c.name().contains(":")).toList();

    assertThat(libraries).isNotEmpty();
    for (OssComponent library : libraries) {
      assertThat(library.licenses())
          .as(library.name())
          .anyMatch(l -> l.spdxId() != null && GATE_ALLOWED.contains(l.spdxId()));
    }
  }

  @Test
  @DisplayName("POM metadata slips are corrected: Spring Session is Apache-2.0")
  void springSessionIsFiledUnderItsRealLicence() {
    assertThat(find(components(), "org.springframework.session:spring-session-core").licenses())
        .extracting(OssLicense::spdxId)
        .containsExactly("Apache-2.0");
  }

  @Test
  @DisplayName("a dual-licensed component appears under each licence, groups sorted by name")
  void groupsByLicence() {
    OssLicenseCatalog catalog =
        catalogOf(
            """
            {"generator":"licensee 1.0","components":[
              {"name":"b:dual","version":"1","modules":["backend"],"licenses":[
                {"spdxId":"MIT","name":"MIT License","url":"https://x"},
                {"spdxId":"Apache-2.0","name":"Apache License 2.0","url":"https://y"}]},
              {"name":"A:only","version":"2","modules":["frontend"],"licenses":[
                {"spdxId":"Apache-2.0","name":"Apache License 2.0","url":"https://y"}]},
              {"name":"Font","version":"3","modules":["frontend"],"licenses":[
                {"spdxId":null,"name":"Custom Font Licence","url":null}]}
            ]}
            """);

    assertThat(catalog.componentCount()).isEqualTo(3);
    assertThat(catalog.groups())
        .extracting(g -> g.license().groupKey())
        .containsExactly("Apache-2.0", "Custom Font Licence", "MIT");
    assertThat(catalog.groups().get(0).components())
        .extracting(OssComponent::name)
        .containsExactly("A:only", "b:dual");
    assertThat(catalog.groups().get(2).components())
        .extracting(OssComponent::name)
        .containsExactly("b:dual");
  }

  @Test
  @DisplayName("a missing report degrades to the unavailable notice instead of failing startup")
  void missingReportIsUnavailable() {
    OssLicenseCatalog catalog =
        new OssLicenseCatalog(mapper, new ClassPathResource("oss/does-not-exist.json"));

    assertThat(catalog.isAvailable()).isFalse();
    assertThat(catalog.groups()).isEmpty();
    assertThat(catalog.componentCount()).isZero();
    assertThat(catalog.generator()).isNull();
  }

  @Test
  @DisplayName("an unreadable report degrades to the unavailable notice")
  void brokenReportIsUnavailable() {
    OssLicenseCatalog catalog = catalogOf("{ this is not json");

    assertThat(catalog.isAvailable()).isFalse();
    assertThat(catalog.groups()).isEmpty();
  }

  /**
   * The components of the report the build generated.
   *
   * @return every component, bundled assets included
   */
  private List<OssComponent> components() {
    return new OssLicenseCatalog(mapper)
        .groups().stream().flatMap(g -> g.components().stream()).distinct().toList();
  }

  /**
   * One component by name, failing the test when it is absent.
   *
   * @param components the components to search
   * @param name the coordinate or product name
   * @return the component
   */
  private static OssComponent find(List<OssComponent> components, String name) {
    return components.stream()
        .filter(c -> c.name().equals(name))
        .findFirst()
        .orElseThrow(() -> new AssertionError(name + " is not in the generated report"));
  }

  /**
   * A catalog over a hand-written report.
   *
   * @param json the report body
   * @return the catalog
   */
  private OssLicenseCatalog catalogOf(String json) {
    Resource resource = new ByteArrayResource(json.getBytes(StandardCharsets.UTF_8));
    return new OssLicenseCatalog(mapper, resource);
  }
}
