{
 "title": "Development / GitHub",
 "tags": [ "basetool" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Stars per repo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "github_repo_stargazers" }
   ]
  },
  {
   "title": "Forks per repo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "github_repo_forks" }
   ]
  },
  {
   "title": "Open issues per repo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "github_repo_issues" }
   ]
  },
  {
   "title": "Watchers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "github_repo_watchers" }
   ]
  },
  {
   "title": "Latest workflow run status",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    { "expr": "github_workflow_run_status" }
   ]
  },
  {
   "title": "Workflow run duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "github_workflow_run_duration_ms"
    }
   ]
  },
  {
   "title": "Non-success workflow statuses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(github_workflow_run_status{status!=\"completed\"})"
    }
   ]
  }
 ]
}