/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.frontend.config;

import java.util.Optional;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.info.BuildProperties;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ModelAttribute;

/**
 * Cross-cutting advice that exposes the deployed application's version string to every Thymeleaf
 * model so the sidebar fragment can render a discreet build-version label under the language
 * switcher.
 *
 * <p>The value is sourced from Spring Boot's auto-configured {@link BuildProperties} bean, which in
 * turn reads {@code META-INF/build-info.properties} generated by the Gradle {@code bootBuildInfo}
 * task (enabled via {@code springBoot { buildInfo() }} in {@code frontend/build.gradle.kts}). The
 * dependency is injected as an {@link Optional} so test slices that do not load {@code
 * ProjectInfoAutoConfiguration} (e.g. {@code @WebMvcTest}) still wire the advice cleanly; in that
 * case the model attribute degrades to a literal {@code "dev"} marker instead of {@code null} so
 * the template never renders an empty version chip.
 *
 * <p>Scoped to {@link UsesLayoutModel}, so it does not run ahead of the module's REST controllers:
 * they serialise through Jackson and never read a model attribute. See that annotation for why the
 * selector is an opt-in marker rather than the {@code Controller} stereotype or a base package. It
 * reaches no backend, but it is layout chrome all the same and follows its four siblings.
 */
@ControllerAdvice(annotations = UsesLayoutModel.class)
@RequiredArgsConstructor
public class AppVersionAdvice {

  /**
   * Fallback string used whenever no {@link BuildProperties} bean is on the context (typical for
   * sliced web-MVC test runs that skip {@code ProjectInfoAutoConfiguration}). Kept short on purpose
   * so the sidebar chip stays unobtrusive in non-prod environments where the canonical Gradle
   * version isn't packaged.
   */
  static final String FALLBACK_VERSION = "dev";

  private final Optional<BuildProperties> buildProperties;

  /**
   * Resolves the version string for the {@code appVersion} Thymeleaf model attribute. Prefers the
   * value read from {@code META-INF/build-info.properties}; falls back to {@link #FALLBACK_VERSION}
   * when the auto-configured bean is absent or its {@code version} field is blank.
   *
   * @return non-{@code null} version string suitable for direct rendering in the sidebar fragment.
   */
  @ModelAttribute("appVersion")
  public String appVersion() {
    return buildProperties
        .map(BuildProperties::getVersion)
        .filter(v -> v != null && !v.isBlank())
        .orElse(FALLBACK_VERSION);
  }
}
