/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.service;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

/**
 * Supplies the version of the Terms of Use currently in force (REQ-SEC-028).
 *
 * <p>The value is a content digest of the terms wording, produced at build time by the root Gradle
 * task {@code generateTermsVersion} from the {@code terms.*} entries of the frontend's German
 * message bundle and delivered here as {@code terms-version.properties} on the classpath. Deriving
 * it from the text is what makes "re-prompt whenever the terms change" impossible to forget: there
 * is no number a human has to remember to bump. An operator who edited the wording purely
 * cosmetically can pin the value for one build with {@code -PtermsVersion=<value>}, which leaves
 * every existing acceptance valid.
 *
 * <p><strong>Fails startup when the resource is absent or blank.</strong> The alternatives are both
 * silent and both wrong: an empty version compared against stored acceptances would either block
 * every user out of the whole API or — if the comparison were made lenient — wave everyone through
 * a gate that looks armed. A refusal to start is loud, happens before any traffic, and points at
 * the one thing that went wrong (the generated resource did not reach the jar).
 */
@Slf4j
@Component
public class TermsVersionProvider {

  /** Classpath location of the generated version file (see the root {@code build.gradle.kts}). */
  static final String RESOURCE_PATH = "terms-version.properties";

  /** Key inside that file; must match what {@code generateTermsVersion} writes. */
  static final String VERSION_KEY = "basetool.terms.version";

  /**
   * The digest of the wording currently in force. Immutable for the process lifetime — a new
   * version can only arrive with a new build, which is why the acceptance cache in {@link
   * TermsAcceptanceService} needs no invalidation on version change.
   */
  @Getter private final String currentVersion;

  /**
   * Reads and validates the generated version resource.
   *
   * @throws IllegalStateException if the resource is missing, unreadable, or carries a blank
   *     version — see the class comment for why this is fatal rather than defaulted
   */
  public TermsVersionProvider() {
    this.currentVersion = readVersion();
    log.info("Terms of Use version in force: {}", currentVersion);
  }

  /**
   * Loads {@value #VERSION_KEY} from {@value #RESOURCE_PATH} on the classpath.
   *
   * @return the trimmed version string, guaranteed non-blank
   * @throws IllegalStateException if the resource is absent, cannot be read, or has no usable value
   */
  private static @NotNull String readVersion() {
    ClassPathResource resource = new ClassPathResource(RESOURCE_PATH);
    if (!resource.exists()) {
      throw new IllegalStateException(
          "Missing "
              + RESOURCE_PATH
              + " on the classpath. It is generated by the root Gradle task generateTermsVersion; "
              + "run the build through Gradle rather than compiling sources directly.");
    }
    Properties properties = new Properties();
    // Reader inside the resource list, not just the stream it wraps: closing the stream alone does
    // release the file descriptor, but leaving the reader out makes the ownership unclear to both
    // readers and static analysis.
    try (Reader reader = new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8)) {
      properties.load(reader);
    } catch (IOException e) {
      throw new IllegalStateException("Cannot read " + RESOURCE_PATH, e);
    }
    String value = properties.getProperty(VERSION_KEY);
    if (value == null || value.isBlank()) {
      throw new IllegalStateException(RESOURCE_PATH + " carries no usable " + VERSION_KEY);
    }
    return value.trim();
  }
}
