/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.service;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

/**
 * Supplies the version of the Terms of Use currently in force (REQ-SEC-028): a build-time content
 * digest of the {@code terms.*} wording, read from {@code terms-version.properties}.
 *
 * <p>Startup fails when the resource is absent or blank.
 */
@Slf4j
@Component
public class TermsVersionProvider {

  /** Classpath location of the generated version file (see the root {@code build.gradle.kts}). */
  static final String RESOURCE_PATH = "terms-version.properties";

  /** Key inside that file; must match what {@code generateTermsVersion} writes. */
  static final String VERSION_KEY = "basetool.terms.version";

  /**
   * The digest of the wording currently in force. Immutable for the process lifetime — a new
   * version can only arrive with a new build, which is why the acceptance cache in {@link
   * TermsAcceptanceService} needs no invalidation on version change.
   */
  @Getter private final String currentVersion;

  /**
   * Reads and validates the generated version resource.
   *
   * @throws IllegalStateException if the resource is missing, unreadable or carries a blank version
   */
  public TermsVersionProvider() {
    this.currentVersion = readVersion();
    log.info("Terms of Use version in force: {}", currentVersion);
  }

  /**
   * Loads {@value #VERSION_KEY} from {@value #RESOURCE_PATH} on the classpath.
   *
   * @return the trimmed version string, guaranteed non-blank
   * @throws IllegalStateException if the resource is absent, cannot be read, or has no usable value
   */
  private static @NotNull String readVersion() {
    ClassPathResource resource = new ClassPathResource(RESOURCE_PATH);
    if (!resource.exists()) {
      throw new IllegalStateException(
          "Missing "
              + RESOURCE_PATH
              + " on the classpath. It is generated by the root Gradle task generateTermsVersion; "
              + "run the build through Gradle rather than compiling sources directly.");
    }
    Properties properties = new Properties();
    try (Reader reader = new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8)) {
      properties.load(reader);
    } catch (IOException e) {
      throw new IllegalStateException("Cannot read " + RESOURCE_PATH, e);
    }
    String value = properties.getProperty(VERSION_KEY);
    if (value == null || value.isBlank()) {
      throw new IllegalStateException(RESOURCE_PATH + " carries no usable " + VERSION_KEY);
    }
    return value.trim();
  }
}
