/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model.dto.request;

import de.greluc.krt.profit.basetool.backend.model.MissionObjectiveKind;
import de.greluc.krt.profit.basetool.backend.validation.DtoConstraints;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.jetbrains.annotations.Nullable;

/**
 * Request DTO for {@code POST /api/v1/missions} and {@code POST /api/v1/missions/{id}/sub-missions}
 * — the create path for missions and sub-missions. Carries only the fields a caller is allowed to
 * set at create time; everything else is stamped server-side:
 *
 * <ul>
 *   <li>{@code id} / {@code version} / {@code coreVersion} / {@code scheduleVersion} / {@code
 *       flagsVersion}: generated by the persistence layer — the structural absence of these fields
 *       on this record makes it impossible for a caller to flip an existing mission's identity or
 *       short-circuit the optimistic-lock check.
 *   <li>{@code owner}: stamped from the authenticated caller in {@link
 *       de.greluc.krt.profit.basetool.backend.service.MissionService#createMission}.
 *   <li>{@code owningSquadron}: stamped via the picker resolver on {@link
 *       de.greluc.krt.profit.basetool.backend.service.OwnerScopeService} in {@code createMission}.
 *       When the caller supplies {@link #owningOrgUnitId}, the resolver validates it against the
 *       owner's memberships and honours it (rejecting Spezialkommando selections with 400 until the
 *       destructive cleanup release loosens NOT NULL on the legacy column). When {@code null}, the
 *       resolver falls back to the owner's home Staffel. Sub-missions inherit from their parent in
 *       {@code addSubMission} and ignore this field.
 *   <li>{@code parent}: stamped from the path variable in {@code addSubMission} — never the body.
 *   <li>{@code managers} / participants / units / frequencies / inventory / refinery: have their
 *       own dedicated endpoints; not part of the create payload.
 *   <li>{@code objectives} (Ziele) / {@code steps} (Ablauf): MAY be seeded here so the create form
 *       can plan goals and steps in the same request (both optional, empty allowed). They remain
 *       editable afterwards through their own {@code /objectives} and {@code /steps} endpoints.
 *       Only the title (and goal classification / step time-place hint) is caller-controllable; the
 *       id, {@code orderIndex} and step done-state are stamped server-side, and no section version
 *       is accepted (a just-created mission has no concurrent editor to lose a race against).
 *   <li>{@code actualStartTime} / {@code actualEndTime}: lifecycle-only fields, set via the {@code
 *       /schedule} patch endpoint or auto-stamped on status transition.
 * </ul>
 *
 * <p>This record is the security boundary for the create path (audit finding C-3): adding a field
 * here is an explicit decision to expose it to the API, while the absence of a field is a
 * structural guarantee that it cannot be smuggled in via JSON. The R5.d.d addition of {@link
 * #owningOrgUnitId} follows that rule — the field is an optional picker output that the service
 * layer validates against the caller's memberships before stamping.
 */
public record CreateMissionRequest(
    @NotBlank @Size(max = 255) String name,
    @Nullable @Size(max = 20000) String description,
    @Nullable
        @Size(max = 2048)
        @Pattern(regexp = DtoConstraints.HTTPS_URL_REGEX, message = "must start with https://")
        String calendarLink,
    @Nullable @Size(max = 64) String status,
    @Nullable Instant meetingTime,
    @Nullable Instant plannedStartTime,
    @Nullable Instant plannedEndTime,
    @Nullable Boolean isInternal,
    @Nullable UUID operationId,
    @Nullable UUID owningOrgUnitId,
    @Nullable @Size(max = 200) String meetingPoint,
    @Nullable List<@Valid NewObjective> objectives,
    @Nullable List<@Valid NewStep> steps) {

  /**
   * A goal (Ziel) to create together with the mission on the {@code POST /api/v1/missions} path, so
   * the create form can seed goals in the same request instead of a follow-up per-goal call.
   * Carries only the title and classification; the id and {@code orderIndex} are assigned
   * server-side and no section version is echoed (a just-created mission has no concurrent editor).
   *
   * @param title the goal text (required, non-blank, at most 500 chars)
   * @param kind the classification (Hauptziel / Nebenziel / Nicht-Ziel)
   */
  public record NewObjective(
      @NotBlank @Size(max = 500) String title, @NotNull MissionObjectiveKind kind) {}

  /**
   * A step (Ablauf-Schritt) to create together with the mission on the {@code POST
   * /api/v1/missions} path. Carries only the title and the optional time/place hint; the id, {@code
   * orderIndex} and the initial not-done state are assigned server-side.
   *
   * @param title the step title (required, non-blank, at most 500 chars)
   * @param meta the optional free-text time/place hint (at most 200 chars)
   */
  public record NewStep(
      @NotBlank @Size(max = 500) String title, @Nullable @Size(max = 200) String meta) {}
}
