/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model.dto.request;

import de.greluc.krt.profit.basetool.backend.model.MissionObjectiveKind;
import de.greluc.krt.profit.basetool.backend.validation.DtoConstraints;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.jetbrains.annotations.Nullable;

/**
 * Request DTO for creating a mission or sub-mission. It carries only the caller-settable fields;
 * the absence of every other field keeps it from being set via JSON.
 *
 * <ul>
 *   <li>{@code id} and all version counters are generated by the persistence layer.
 *   <li>{@code owner} is stamped from the authenticated caller.
 *   <li>{@code owningSquadron} is resolved from {@link #owningOrgUnitId} through {@link
 *       de.greluc.krt.profit.basetool.backend.service.OwnerScopeService}. Sub-missions inherit
 *       their parent's and ignore it.
 *   <li>{@code parent} comes from the path variable.
 *   <li>Managers, participants, units, frequencies, inventory and refinery have their own
 *       endpoints.
 *   <li>{@code objectives} and {@code steps} may be seeded here; ids, order and done-state are
 *       assigned server-side.
 *   <li>{@code actualStartTime} / {@code actualEndTime} are set via {@code /schedule} or on status
 *       transition.
 * </ul>
 *
 * <p>{@link #owningOrgUnitId} is honoured when it is a direct membership of the owner or an
 * editable org unit (REQ-ORG-016); when {@code null}, a single membership or the active-context pin
 * (REQ-ORG-017) decides, a multi-membership owner gets 400, and a membershipless leadership owner
 * creates an ownerless mission.
 */
public record CreateMissionRequest(
    @NotBlank @Size(max = 255) String name,
    @Nullable @Size(max = 20000) String description,
    @Nullable
        @Size(max = 2048)
        @Pattern(regexp = DtoConstraints.HTTPS_URL_REGEX, message = "must start with https://")
        String calendarLink,
    @Nullable @Size(max = 64) String status,
    @Nullable Instant meetingTime,
    @Nullable Instant plannedStartTime,
    @Nullable Instant plannedEndTime,
    @Nullable Boolean isInternal,
    @Nullable UUID operationId,
    @Nullable UUID owningOrgUnitId,
    @Nullable @Size(max = 200) String meetingPoint,
    @Nullable List<@Valid NewObjective> objectives,
    @Nullable List<@Valid NewStep> steps) {

  /**
   * A goal (Ziel) created together with the mission; id and {@code orderIndex} are assigned
   * server-side.
   *
   * @param title the goal text (required, non-blank, at most 500 chars)
   * @param kind the classification (Hauptziel / Nebenziel / Nicht-Ziel)
   */
  public record NewObjective(
      @NotBlank @Size(max = 500) String title, @NotNull MissionObjectiveKind kind) {}

  /**
   * A step (Ablauf-Schritt) to create together with the mission on the {@code POST
   * /api/v1/missions} path. Carries only the title and the optional time/place hint; the id, {@code
   * orderIndex} and the initial not-done state are assigned server-side.
   *
   * @param title the step title (required, non-blank, at most 500 chars)
   * @param meta the optional free-text time/place hint (at most 200 chars)
   */
  public record NewStep(
      @NotBlank @Size(max = 500) String title, @Nullable @Size(max = 200) String meta) {}
}
