#!/usr/bin/env bash

# shellcheck disable=SC2016

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RENDERER="${SCRIPT_DIR}/render-env-d.py"
PY="${PYTHON:-python3}"

if [[ ! -f "$RENDERER" ]]; then
  echo "FATAL: renderer not found at ${RENDERER}" >&2
  exit 1
fi

PASSED=0
FAILED=0
say() { printf '%s\n' "$*"; }
ok()  { PASSED=$((PASSED + 1)); printf '  ok    %s\n' "$*"; }
bad() { FAILED=$((FAILED + 1)); printf '  FAIL  %s\n' "$*"; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/render-env-d-test.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

scenario() {
  SC_DIR="${WORK}/$1"
  mkdir -p "${SC_DIR}/tmpl" "${SC_DIR}/out"
  printf '%s\n' "$2" > "${SC_DIR}/env"
  printf '%s\n' "$3" > "${SC_DIR}/tmpl/svc.env.tmpl"
}

render() { "$PY" "$RENDERER" --env "${SC_DIR}/env" --templates "${SC_DIR}/tmpl" --out "${SC_DIR}/out" "$@"; }
rendered() { cat "${SC_DIR}/out/svc.env" 2>/dev/null; }

expect_line() {
  local name="$1" envc="$2" tmpl="$3" want="$4"
  scenario "$name" "$envc" "$tmpl"
  if ! render >/dev/null 2>&1; then
    bad "${name}: renderer exited non-zero"
    return
  fi
  if rendered | grep -qxF "$want"; then
    ok "${name}"
  else
    bad "${name}: wanted ${want@Q}, got: $(rendered | grep -v '^#' | tr '\n' '|')"
  fi
}

say ""
say "== interpolation semantics, as compose defines them =="
expect_line "plain_reference"        'A=yes'            'K=${A}'                      'K=yes'
expect_line "unset_is_empty"         'A=yes'            'K=${MISSING}'                'K='
expect_line "default_when_unset"     'A=yes'            'K=${MISSING:-fallback}'      'K=fallback'
expect_line "colon_dash_takes_empty" 'E='               'K=${E:-fallback}'            'K=fallback'
expect_line "bare_dash_keeps_empty"  'E='               'K=${E-fallback}'             'K='
expect_line "set_beats_default"      'A=yes'            'K=${A:-fallback}'            'K=yes'
expect_line "embedded_in_a_string"   'A=yes'            'K=pre-${A}-post'             'K=pre-yes-post'

expect_line "nested_default" \
  'H=https://x.example/auth' \
  'K=${ISS:-${H:-https://fallback/auth}/realms/iri}' \
  'K=https://x.example/auth/realms/iri'
expect_line "nested_default_all_unset" \
  '# nothing set' \
  'K=${ISS:-${H:-https://fallback/auth}/realms/iri}' \
  'K=https://fallback/auth/realms/iri'

expect_line "dollar_in_value"        'P=aa$bb-cc'       'K=${P}'                      'K=aa$bb-cc'
expect_line "quotes_are_stripped"    'P="quoted"'       'K=${P}'                      'K=quoted'

say ""
say "== a required variable that is missing stops everything =="
scenario "refuses_and_writes_nothing" '# empty' 'K=${NEEDED:?NEEDED must be set in .env}'
if render >/dev/null 2>&1; then
  bad "refuses_and_writes_nothing: renderer exited 0 on a missing required variable"
else
  ok "refuses_and_writes_nothing: non-zero exit"
fi
if [[ -f "${SC_DIR}/out/svc.env" ]]; then
  bad "refuses_and_writes_nothing: it wrote a file anyway"
else
  ok "refuses_and_writes_nothing: nothing was written"
fi
refusal="$(render 2>&1)"
if printf '%s' "$refusal" | grep -qF 'NEEDED must be set in .env'; then
  ok "refuses_and_writes_nothing: the message names the variable and its reason"
else
  bad "refuses_and_writes_nothing: the refusal did not carry the template's message"
fi

scenario "colon_question_rejects_empty" 'NEEDED=' 'K=${NEEDED:?must be set}'
if render >/dev/null 2>&1; then
  bad "colon_question_rejects_empty: an empty value satisfied \${NAME:?}"
else
  ok "colon_question_rejects_empty"
fi

scenario "bare_question_accepts_empty" 'NEEDED=' 'K=${NEEDED?must be set}'
if render >/dev/null 2>&1; then
  ok "bare_question_accepts_empty"
else
  bad "bare_question_accepts_empty: \${NAME?} wrongly rejected a set-but-empty value"
fi

scenario "reports_every_missing" '# empty' 'A=${ONE:?first}
B=${TWO:?second}
C=${THREE:?third}'
out="$(render 2>&1)"
count=$(printf '%s\n' "$out" | grep -cE '^\s+(ONE|TWO|THREE) ')
if [[ "$count" -eq 3 ]]; then
  ok "reports_every_missing: all three named in one run"
else
  bad "reports_every_missing: named ${count} of 3"
fi

say ""
say "== the generated header must survive verbatim =="
HEADER='# Generated by scripts/generate-quadlet.py -- do not edit. Run the generator.
# A literal passes through; a ${NAME:-default} keeps its default when the host
# sets nothing; a ${NAME:?...} must be set or the render fails.'
scenario "header_survives" 'A=yes' "${HEADER}
K=\${A}"
if render >/dev/null 2>&1; then
  if rendered | grep -qF 'a ${NAME:-default} keeps its default' \
     && rendered | grep -qF 'a ${NAME:?...} must be set'; then
    ok "header_survives: the comment's own examples are untouched"
  else
    bad "header_survives: the header was interpolated -- its examples were mangled"
  fi
  ok "header_survives: a \${NAME:?} inside a comment does not refuse the render"
else
  bad "header_survives: a \${NAME:?...} in a COMMENT wrongly refused the whole render"
fi

say ""
say "== --check reports drift and writes nothing =="
scenario "check_detects_drift" 'A=yes' 'K=${A}'
render >/dev/null 2>&1
if render --check >/dev/null 2>&1; then
  ok "check_detects_drift: clean after a render"
else
  bad "check_detects_drift: reported drift against its own output"
fi
printf 'K=tampered\n' > "${SC_DIR}/out/svc.env"
if render --check >/dev/null 2>&1; then
  bad "check_detects_drift: did not notice a tampered file"
else
  ok "check_detects_drift: a tampered file is drift"
fi
if grep -qx 'K=tampered' "${SC_DIR}/out/svc.env"; then
  ok "check_detects_drift: --check wrote nothing"
else
  bad "check_detects_drift: --check overwrote the file it was only asked to inspect"
fi

scenario "check_detects_absence" 'A=yes' 'K=${A}'
if render --check >/dev/null 2>&1; then
  bad "check_detects_absence: an absent output file read as clean"
else
  ok "check_detects_absence"
fi

say ""
say "== one file per service, which is what keeps the allow-list closed =="
SC_DIR="${WORK}/per_service"
mkdir -p "${SC_DIR}/tmpl" "${SC_DIR}/out"
printf 'SHARED=s\nONLY_A=a\n' > "${SC_DIR}/env"
printf 'K=${SHARED}\nSECRET=${ONLY_A}\n' > "${SC_DIR}/tmpl/alpha.env.tmpl"
printf 'K=${SHARED}\n'                   > "${SC_DIR}/tmpl/beta.env.tmpl"
if render >/dev/null 2>&1; then
  if [[ -f "${SC_DIR}/out/alpha.env" && -f "${SC_DIR}/out/beta.env" ]]; then
    ok "per_service: one output file per template"
  else
    bad "per_service: expected alpha.env and beta.env"
  fi
  if grep -q 'SECRET=' "${SC_DIR}/out/beta.env" 2>/dev/null; then
    bad "per_service: beta received a variable its own template never named"
  else
    ok "per_service: beta sees only what its template names"
  fi
else
  bad "per_service: renderer exited non-zero"
fi

probe="${WORK}/mode-probe"
: > "$probe"; chmod 640 "$probe" 2>/dev/null
if [[ "$(stat -c '%a' "$probe" 2>/dev/null)" == "640" ]]; then
  actual="$(stat -c '%a' "${SC_DIR}/out/alpha.env" 2>/dev/null)"
  if [[ "$actual" == "640" ]]; then
    ok "per_service: written 0640"
  else
    bad "per_service: mode is ${actual}, wanted 640"
  fi
else
  say "  skip  per_service: this filesystem cannot express Unix modes (chmod 640 did not stick)"
fi

say ""
say "== a retired service's rendered secrets do not stay on the host =="
scenario "stale" 'A=yes' 'K=${A}'
printf 'OLD_SECRET=leftover\n' > "${SC_DIR}/out/retired.env"

if render --check >/dev/null 2>"${SC_DIR}/check.err"; then
  bad "stale: --check reported success with an orphaned retired.env present"
else
  if grep -q 'retired.env' "${SC_DIR}/check.err"; then
    ok "stale: --check names the orphaned file"
  else
    bad "stale: --check failed but did not name retired.env: $(cat "${SC_DIR}/check.err")"
  fi
fi

printf 'keep me\n' > "${SC_DIR}/out/notes.txt"
render >"${SC_DIR}/write.out" 2>&1
if [[ -e "${SC_DIR}/out/retired.env" ]]; then
  bad "stale: a plain run left retired.env behind"
else
  ok "stale: a plain run removes it"
fi
if grep -q 'removed retired.env' "${SC_DIR}/write.out"; then
  ok "stale: the removal is named, not silently counted"
else
  bad "stale: the removal was not reported: $(cat "${SC_DIR}/write.out")"
fi
if [[ -e "${SC_DIR}/out/notes.txt" ]]; then
  ok "stale: a non-.env file in the same directory is left alone"
else
  bad "stale: notes.txt was deleted -- the removal is not bounded to *.env"
fi
if render --check >/dev/null 2>&1; then
  ok "stale: --check is clean once the leftover is gone"
else
  bad "stale: --check still red after the cleanup run"
fi

say ""
say "-- an unwritable existing target --"
scenario "readonly" 'A=yes' 'K=${A}'
render >/dev/null 2>&1
chmod 0400 "${SC_DIR}/out/svc.env"
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    say "  skip  readonly target - os.replace over a read-only file is denied on Windows"
    chmod 0640 "${SC_DIR}/out/svc.env"
    ;;
  *)
if : > "${SC_DIR}/out/svc.env" 2>/dev/null; then
  say "  skip  readonly target - running as a user that ignores mode bits (root?)"
  chmod 0640 "${SC_DIR}/out/svc.env"
else
  if render >"${SC_DIR}/ro.out" 2>&1; then
    ok "readonly: a 0400 svc.env is replaced rather than opened"
  else
    bad "readonly: render failed on a 0400 target: $(cat "${SC_DIR}/ro.out")"
  fi
  if grep -q 'K=yes' "${SC_DIR}/out/svc.env" 2>/dev/null; then
    ok "readonly: and the new content is what landed"
  else
    bad "readonly: the file was not updated: $(cat "${SC_DIR}/out/svc.env" 2>/dev/null)"
  fi
  if [[ "$(stat -c '%a' "${SC_DIR}/out/svc.env")" == "640" ]]; then
    ok "readonly: the replacement carries the requested mode, not the old one"
  else
    bad "readonly: mode is $(stat -c '%a' "${SC_DIR}/out/svc.env"), expected 640"
  fi
fi
    ;;
esac
if find "${SC_DIR}/out" -maxdepth 1 -name '.*.tmp' | grep -q .; then
  bad "readonly: a temporary sibling was left behind"
else
  ok "readonly: no temporary sibling is left behind"
fi

say ""
say "=========================================="
say "  passed: ${PASSED}   failed: ${FAILED}"
say "=========================================="
[[ "$FAILED" -eq 0 ]] || exit 1
