apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: grafana
    jsonData:
      httpMethod: POST
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_WEB_PASSWORD}
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: '"traceId":"(\w+)"'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View trace'
    editable: false

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        tags:
          - key: 'service.name'
            value: 'application'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    editable: false
