spring:
  datasource:
    url: jdbc:postgresql://db-backend:15432/krt_basetool
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://profit-base.online/auth/realms/iri}

krt:
  scwiki:
    scheduler-enabled: true
    commodity-sync-enabled: true
    vehicle-sync-enabled: true
    item-sync-enabled: true
    blueprint-sync-enabled: true
    manufacturer-sync-enabled: true
    sync-all-items: true
    reconcile-uuidless-by-name: true

app:
  security:
    jwt:
      jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:}
