spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://profit-base.online/auth/realms/iri}

app:
  ingest:
    backend-base-url: ${BACKEND_URL:https://localhost:11261}
    frontend-base-url: ${FRONTEND_URL:http://localhost:18081}

logging:
  level:
    de.greluc.krt.profit.basetool.ingest: DEBUG
